// Quick script to generate comprehensive product catalog SQL
// Run with: npx tsx supabase/generate_products.ts > supabase/seed_all_products.sql

type Product = {
  id: string;
  category: string;
  name: string;
  unit: string;
  price: number;
  description: string;
};

const products: Product[] = [
  // ============================================================================
  // FRAMING (Builders) - 42 products
  // ============================================================================
  { id: '2x4-stud-8ft', category: 'framing', name: '2x4x8 KD Stud', unit: 'EA', price: 3.45, description: 'Kiln-dried framing stud' },
  { id: '2x4-stud-precut', category: 'framing', name: '2x4x92-5/8 Precut Stud', unit: 'EA', price: 3.65, description: 'Precut stud for 8ft walls' },
  { id: '2x6-stud-8ft', category: 'framing', name: '2x6x8 KD Stud', unit: 'EA', price: 6.25, description: 'Kiln-dried stud' },
  { id: '2x4-plate-10ft', category: 'framing', name: '2x4 Plate 10ft', unit: 'EA', price: 6.90, description: 'Top/bottom plate' },
  { id: '2x4-plate-12ft', category: 'framing', name: '2x4 Plate 12ft', unit: 'EA', price: 8.15, description: 'Top/bottom plate' },
  { id: '2x6-plate-10ft', category: 'framing', name: '2x6 Plate 10ft', unit: 'EA', price: 11.50, description: 'Top/bottom plate' },
  { id: '2x8-joist-10ft', category: 'framing', name: '2x8 Joist 10ft', unit: 'EA', price: 14.25, description: 'Floor/ceiling joist' },
  { id: '2x8-joist-12ft', category: 'framing', name: '2x8 Joist 12ft', unit: 'EA', price: 17.50, description: 'Floor/ceiling joist' },
  { id: '2x10-joist-12ft', category: 'framing', name: '2x10 Joist 12ft', unit: 'EA', price: 24.75, description: 'Floor/ceiling joist' },
  { id: '2x12-joist-12ft', category: 'framing', name: '2x12 Joist 12ft', unit: 'EA', price: 32.50, description: 'Floor/ceiling joist' },
  { id: '4x4-post-8ft', category: 'framing', name: '4x4x8 Post', unit: 'EA', price: 18.50, description: 'Structural post' },
  { id: '4x4-post-10ft', category: 'framing', name: '4x4x10 Post', unit: 'EA', price: 23.75, description: 'Structural post' },
  { id: '6x6-post-8ft', category: 'framing', name: '6x6x8 Post', unit: 'EA', price: 42.00, description: 'Heavy structural post' },
  { id: 'lvl-header-2x10-12ft', category: 'framing', name: 'LVL Header 2x10 12ft', unit: 'EA', price: 54.00, description: 'Engineered header' },
  { id: 'lvl-beam-3-5x14-16ft', category: 'framing', name: 'LVL Beam 3.5x14 16ft', unit: 'EA', price: 125.00, description: 'Engineered beam' },
  { id: 'osb-7-16-4x8', category: 'framing', name: 'OSB 7/16 in 4x8', unit: 'SHEET', price: 14.25, description: 'Sheathing' },
  { id: 'osb-1-2-4x8', category: 'framing', name: 'OSB 1/2 in 4x8', unit: 'SHEET', price: 16.50, description: 'Sheathing' },
  { id: 'osb-5-8-4x8', category: 'framing', name: 'OSB 5/8 in 4x8', unit: 'SHEET', price: 19.75, description: 'Subfloor' },
  { id: 'osb-3-4-4x8', category: 'framing', name: 'OSB 3/4 in 4x8', unit: 'SHEET', price: 24.00, description: 'Subfloor' },
  { id: 'plywood-1-2-4x8', category: 'framing', name: 'Plywood 1/2 in 4x8', unit: 'SHEET', price: 38.50, description: 'Sheathing' },
  { id: 'plywood-5-8-4x8', category: 'framing', name: 'Plywood 5/8 in 4x8', unit: 'SHEET', price: 42.75, description: 'Subfloor' },
  { id: 'plywood-3-4-4x8', category: 'framing', name: 'Plywood 3/4 in 4x8', unit: 'SHEET', price: 48.50, description: 'Subfloor' },
  { id: 'treated-4x4-8ft', category: 'framing', name: 'Treated 4x4x8 Post', unit: 'EA', price: 22.50, description: 'Pressure treated' },
  { id: 'treated-2x6-8ft', category: 'framing', name: 'Treated 2x6x8', unit: 'EA', price: 9.75, description: 'Pressure treated' },
  { id: 'treated-2x8-10ft', category: 'framing', name: 'Treated 2x8x10', unit: 'EA', price: 18.50, description: 'Pressure treated' },
  { id: 'treated-plywood-1-2-4x8', category: 'framing', name: 'Treated Plywood 1/2 in 4x8', unit: 'SHEET', price: 45.00, description: 'Exterior grade' },
  { id: 'treated-plywood-3-4-4x8', category: 'framing', name: 'Treated Plywood 3/4 in 4x8', unit: 'SHEET', price: 58.00, description: 'Exterior grade' },
  { id: 'joist-hanger-2x6', category: 'framing', name: 'Joist Hanger 2x6', unit: 'EA', price: 1.65, description: 'Galvanized' },
  { id: 'joist-hanger-2x8', category: 'framing', name: 'Joist Hanger 2x8', unit: 'EA', price: 1.85, description: 'Galvanized' },
  { id: 'joist-hanger-2x10', category: 'framing', name: 'Joist Hanger 2x10', unit: 'EA', price: 2.15, description: 'Galvanized' },
  { id: 'joist-hanger-2x12', category: 'framing', name: 'Joist Hanger 2x12', unit: 'EA', price: 2.65, description: 'Galvanized' },
  { id: 'hurricane-tie-h2-5', category: 'framing', name: 'Hurricane Tie H2.5', unit: 'EA', price: 1.25, description: 'Roof tie-down' },
  { id: 'hurricane-tie-h10', category: 'framing', name: 'Hurricane Tie H10', unit: 'EA', price: 3.85, description: 'Heavy duty tie' },
  { id: 'post-base-4x4', category: 'framing', name: 'Post Base 4x4', unit: 'EA', price: 4.25, description: 'Galvanized base' },
  { id: 'post-cap-4x4', category: 'framing', name: 'Post Cap 4x4', unit: 'EA', price: 3.75, description: 'Galvanized cap' },
  { id: 'simpson-lsu-hanger', category: 'framing', name: 'Simpson LSU Hanger', unit: 'EA', price: 4.85, description: 'Face mount hanger' },
  { id: 'mending-plate-6in', category: 'framing', name: 'Mending Plate 6 in', unit: 'EA', price: 2.15, description: 'Galvanized' },
  { id: 'tie-plate-5in', category: 'framing', name: 'Tie Plate 5 in', unit: 'EA', price: 1.85, description: 'Galvanized' },
  { id: 'angle-bracket-3x3', category: 'framing', name: 'Angle Bracket 3x3', unit: 'EA', price: 1.95, description: '90 degree bracket' },
  { id: 'rim-board-lvl-9-5x1-75-16ft', category: 'framing', name: 'LVL Rim Board 9.5x1.75 16ft', unit: 'EA', price: 68.00, description: 'Engineered rim' },
  { id: 'i-joist-9-5-16ft', category: 'framing', name: 'I-Joist 9-1/2 in 16ft', unit: 'EA', price: 32.50, description: 'Engineered joist' },
  { id: 'i-joist-11-7-16ft', category: 'framing', name: 'I-Joist 11-7/8 in 16ft', unit: 'EA', price: 38.75, description: 'Engineered joist' },

  // ============================================================================
  // FASTENERS - 60 products
  // ============================================================================
  { id: 'nails-16d-framing-5lb', category: 'fasteners', name: '16d Framing Nails (5 lb)', unit: 'BOX', price: 18.50, description: 'Hot-dipped galvanized' },
  { id: 'nails-16d-framing-50lb', category: 'fasteners', name: '16d Framing Nails (50 lb)', unit: 'BOX', price: 165.00, description: 'Bulk box' },
  { id: 'nails-8d-common-5lb', category: 'fasteners', name: '8d Common Nails (5 lb)', unit: 'BOX', price: 16.25, description: 'Bright finish' },
  { id: 'nails-10d-common-5lb', category: 'fasteners', name: '10d Common Nails (5 lb)', unit: 'BOX', price: 17.00, description: 'Bright finish' },
  { id: 'nails-6d-finish-1lb', category: 'fasteners', name: '6d Finish Nails (1 lb)', unit: 'BOX', price: 5.25, description: 'Trim nails' },
  { id: 'nails-8d-finish-1lb', category: 'fasteners', name: '8d Finish Nails (1 lb)', unit: 'BOX', price: 5.75, description: 'Trim nails' },
  { id: 'nails-4d-box-1lb', category: 'fasteners', name: '4d Box Nails (1 lb)', unit: 'BOX', price: 4.50, description: 'Thin shank' },
  { id: 'nails-6d-box-5lb', category: 'fasteners', name: '6d Box Nails (5 lb)', unit: 'BOX', price: 15.50, description: 'Thin shank' },
  { id: 'nails-roofing-1-25-5lb', category: 'fasteners', name: 'Roofing Nails 1-1/4 in (5 lb)', unit: 'BOX', price: 19.75, description: 'Galvanized' },
  { id: 'nails-roofing-1-75-5lb', category: 'fasteners', name: 'Roofing Nails 1-3/4 in (5 lb)', unit: 'BOX', price: 21.50, description: 'Galvanized' },
  { id: 'nails-siding-2-5lb', category: 'fasteners', name: 'Siding Nails 2 in (5 lb)', unit: 'BOX', price: 18.25, description: 'Ring shank' },
  { id: 'nails-duplex-3in-5lb', category: 'fasteners', name: 'Duplex Nails 3 in (5 lb)', unit: 'BOX', price: 19.50, description: 'Double-headed' },
  { id: 'nails-concrete-2-5in-1lb', category: 'fasteners', name: 'Concrete Nails 2-1/2 in (1 lb)', unit: 'BOX', price: 8.75, description: 'Hardened steel' },
  { id: 'nails-brad-18ga-1in', category: 'fasteners', name: 'Brad Nails 18ga 1 in (5000)', unit: 'BOX', price: 12.50, description: 'For nailer' },
  { id: 'nails-brad-18ga-1-5in', category: 'fasteners', name: 'Brad Nails 18ga 1-1/2 in (5000)', unit: 'BOX', price: 14.25, description: 'For nailer' },
  { id: 'screws-deck-2-5in-1lb', category: 'fasteners', name: 'Deck Screws 2-1/2 in (1 lb)', unit: 'BOX', price: 8.50, description: 'Coated' },
  { id: 'screws-deck-3in-5lb', category: 'fasteners', name: 'Deck Screws 3 in (5 lb)', unit: 'BOX', price: 32.00, description: 'Coated' },
  { id: 'screws-construction-3in-1lb', category: 'fasteners', name: 'Construction Screws 3 in (1 lb)', unit: 'BOX', price: 9.75, description: 'Multi-purpose' },
  { id: 'screws-wood-1-5-8-1lb', category: 'fasteners', name: 'Wood Screws 1-5/8 in (1 lb)', unit: 'BOX', price: 7.25, description: 'Coarse thread' },
  { id: 'screws-wood-2in-1lb', category: 'fasteners', name: 'Wood Screws 2 in (1 lb)', unit: 'BOX', price: 7.75, description: 'Coarse thread' },
  { id: 'screws-drywall-1-25in-1lb', category: 'fasteners', name: 'Drywall Screws 1-1/4 in (1 lb)', unit: 'BOX', price: 6.50, description: 'Fine thread' },
  { id: 'screws-drywall-1-5-8in-5lb', category: 'fasteners', name: 'Drywall Screws 1-5/8 in (5 lb)', unit: 'BOX', price: 24.00, description: 'Fine thread' },
  { id: 'screws-cabinet-1-25in', category: 'fasteners', name: 'Cabinet Screws 1-1/4 in (100)', unit: 'BOX', price: 5.75, description: 'Trim head' },
  { id: 'screws-cabinet-2in', category: 'fasteners', name: 'Cabinet Screws 2 in (100)', unit: 'BOX', price: 6.50, description: 'Trim head' },
  { id: 'screws-lag-1-2x4', category: 'fasteners', name: 'Lag Screws 1/2 x 4 in (25)', unit: 'BOX', price: 12.50, description: 'Hex head' },
  { id: 'screws-lag-1-2x6', category: 'fasteners', name: 'Lag Screws 1/2 x 6 in (25)', unit: 'BOX', price: 15.75, description: 'Hex head' },
  { id: 'screws-structural-5in', category: 'fasteners', name: 'Structural Screws 5 in (50)', unit: 'BOX', price: 24.50, description: 'GRK or equivalent' },
  { id: 'screws-structural-6in', category: 'fasteners', name: 'Structural Screws 6 in (50)', unit: 'BOX', price: 28.75, description: 'GRK or equivalent' },
  { id: 'bolts-carriage-1-2x6', category: 'fasteners', name: 'Carriage Bolts 1/2 x 6 in (25)', unit: 'BOX', price: 18.50, description: 'With nuts' },
  { id: 'bolts-carriage-1-2x8', category: 'fasteners', name: 'Carriage Bolts 1/2 x 8 in (25)', unit: 'BOX', price: 22.00, description: 'With nuts' },
  { id: 'bolts-hex-3-8x4', category: 'fasteners', name: 'Hex Bolts 3/8 x 4 in (50)', unit: 'BOX', price: 16.25, description: 'With nuts/washers' },
  { id: 'bolts-hex-1-2x5', category: 'fasteners', name: 'Hex Bolts 1/2 x 5 in (25)', unit: 'BOX', price: 19.50, description: 'With nuts/washers' },
  { id: 'anchors-wedge-1-2x3', category: 'fasteners', name: 'Wedge Anchors 1/2 x 3 in (25)', unit: 'BOX', price: 24.50, description: 'Concrete anchors' },
  { id: 'anchors-sleeve-3-8x2-5', category: 'fasteners', name: 'Sleeve Anchors 3/8 x 2-1/2 in (50)', unit: 'BOX', price: 28.00, description: 'Concrete anchors' },
  { id: 'anchors-tapcon-1-4x2-25', category: 'fasteners', name: 'Tapcon Screws 1/4 x 2-1/4 in (100)', unit: 'BOX', price: 18.75, description: 'Blue concrete screws' },
  { id: 'anchors-toggle-1-4', category: 'fasteners', name: 'Toggle Bolts 1/4 in (25)', unit: 'BOX', price: 8.50, description: 'Hollow wall anchors' },
  { id: 'anchors-molly-1-4', category: 'fasteners', name: 'Molly Bolts 1/4 in (50)', unit: 'BOX', price: 12.25, description: 'Hollow wall anchors' },
  { id: 'staples-t50-1-4in', category: 'fasteners', name: 'T50 Staples 1/4 in (5000)', unit: 'BOX', price: 8.75, description: 'Heavy duty' },
  { id: 'staples-t50-3-8in', category: 'fasteners', name: 'T50 Staples 3/8 in (5000)', unit: 'BOX', price: 9.50, description: 'Heavy duty' },
  { id: 'staples-crown-15ga-1in', category: 'fasteners', name: 'Crown Staples 15ga 1 in (5000)', unit: 'BOX', price: 14.50, description: 'For nailer' },
  { id: 'nails-framing-21deg-3in', category: 'fasteners', name: 'Framing Nails 21° 3 in (2000)', unit: 'BOX', price: 38.00, description: 'For nailer' },
  { id: 'nails-framing-21deg-3-25in', category: 'fasteners', name: 'Framing Nails 21° 3-1/4 in (2000)', unit: 'BOX', price: 42.50, description: 'For nailer' },
  { id: 'nails-coil-120-2-5in', category: 'fasteners', name: 'Coil Nails 120° 2-1/2 in (3600)', unit: 'BOX', price: 48.00, description: 'For coil nailer' },
  { id: 'nails-siding-coil-2-5in', category: 'fasteners', name: 'Siding Coil Nails 2-1/2 in (3600)', unit: 'BOX', price: 52.00, description: 'Ring shank' },
  { id: 'adhesive-construction-28oz', category: 'fasteners', name: 'Construction Adhesive 28 oz', unit: 'TUBE', price: 5.75, description: 'Heavy duty' },
  { id: 'adhesive-pl-premium-28oz', category: 'fasteners', name: 'PL Premium Adhesive 28 oz', unit: 'TUBE', price: 6.50, description: 'All-weather' },
  { id: 'adhesive-liquid-nails-28oz', category: 'fasteners', name: 'Liquid Nails 28 oz', unit: 'TUBE', price: 5.25, description: 'Multi-purpose' },
  { id: 'adhesive-subfloor-28oz', category: 'fasteners', name: 'Subfloor Adhesive 28 oz', unit: 'TUBE', price: 7.25, description: 'Prevents squeaks' },
  { id: 'adhesive-panel-10oz', category: 'fasteners', name: 'Panel Adhesive 10 oz', unit: 'TUBE', price: 4.50, description: 'For paneling' },
  { id: 'caulk-latex-10oz', category: 'fasteners', name: 'Latex Caulk 10 oz', unit: 'TUBE', price: 3.25, description: 'Paintable' },
  { id: 'caulk-silicone-10oz', category: 'fasteners', name: 'Silicone Caulk 10 oz', unit: 'TUBE', price: 4.75, description: 'Waterproof' },
  { id: 'caulk-exterior-10oz', category: 'fasteners', name: 'Exterior Caulk 10 oz', unit: 'TUBE', price: 5.50, description: 'Weather resistant' },
  { id: 'foam-gap-filler-12oz', category: 'fasteners', name: 'Expanding Foam 12 oz', unit: 'CAN', price: 6.25, description: 'Gap filler' },
  { id: 'foam-window-door-12oz', category: 'fasteners', name: 'Window/Door Foam 12 oz', unit: 'CAN', price: 7.50, description: 'Minimal expansion' },
  { id: 'epoxy-2part-1oz', category: 'fasteners', name: '2-Part Epoxy 1 oz', unit: 'TUBE', price: 5.75, description: 'High strength' },
  { id: 'epoxy-2part-10oz', category: 'fasteners', name: '2-Part Epoxy 10 oz', unit: 'TUBE', price: 12.50, description: 'High strength' },
  { id: 'wood-glue-8oz', category: 'fasteners', name: 'Wood Glue 8 oz', unit: 'BOTTLE', price: 4.25, description: 'Yellow glue' },
  { id: 'wood-glue-16oz', category: 'fasteners', name: 'Wood Glue 16 oz', unit: 'BOTTLE', price: 6.75, description: 'Yellow glue' },
  { id: 'wood-glue-weatherproof-16oz', category: 'fasteners', name: 'Weatherproof Wood Glue 16 oz', unit: 'BOTTLE', price: 8.50, description: 'Type II' },

  // ============================================================================
  // DRYWALL - 50 products
  // ============================================================================
  { id: 'drywall-1-2-4x8', category: 'drywall', name: 'Drywall 1/2 in 4x8', unit: 'SHEET', price: 14.50, description: 'Standard drywall' },
  { id: 'drywall-1-2-4x10', category: 'drywall', name: 'Drywall 1/2 in 4x10', unit: 'SHEET', price: 17.75, description: 'Standard drywall' },
  { id: 'drywall-1-2-4x12', category: 'drywall', name: 'Drywall 1/2 in 4x12', unit: 'SHEET', price: 21.00, description: 'Standard drywall' },
  { id: 'drywall-5-8-4x8', category: 'drywall', name: 'Drywall 5/8 in 4x8', unit: 'SHEET', price: 16.25, description: 'Fire-rated Type X' },
  { id: 'drywall-5-8-4x12', category: 'drywall', name: 'Drywall 5/8 in 4x12', unit: 'SHEET', price: 23.50, description: 'Fire-rated Type X' },
  { id: 'drywall-1-4-4x8', category: 'drywall', name: 'Drywall 1/4 in 4x8', unit: 'SHEET', price: 12.75, description: 'Ceiling repair' },
  { id: 'drywall-moisture-1-2-4x8', category: 'drywall', name: 'Moisture-Resistant Drywall 1/2 in 4x8', unit: 'SHEET', price: 18.50, description: 'Green board' },
  { id: 'drywall-moisture-5-8-4x8', category: 'drywall', name: 'Moisture-Resistant Drywall 5/8 in 4x8', unit: 'SHEET', price: 21.00, description: 'Green board' },
  { id: 'drywall-mold-1-2-4x8', category: 'drywall', name: 'Mold-Resistant Drywall 1/2 in 4x8', unit: 'SHEET', price: 22.50, description: 'Purple board' },
  { id: 'cement-board-1-2-3x5', category: 'drywall', name: 'Cement Board 1/2 in 3x5', unit: 'SHEET', price: 18.75, description: 'Tile backer' },
  { id: 'cement-board-1-2-4x8', category: 'drywall', name: 'Cement Board 1/2 in 4x8', unit: 'SHEET', price: 28.50, description: 'Tile backer' },
  { id: 'cement-board-5-8-3x5', category: 'drywall', name: 'Cement Board 5/8 in 3x5', unit: 'SHEET', price: 21.50, description: 'Tile backer' },
  { id: 'tape-paper-2in-250ft', category: 'drywall', name: 'Paper Tape 2 in x 250 ft', unit: 'ROLL', price: 4.25, description: 'Joint tape' },
  { id: 'tape-paper-2in-500ft', category: 'drywall', name: 'Paper Tape 2 in x 500 ft', unit: 'ROLL', price: 7.50, description: 'Joint tape' },
  { id: 'tape-mesh-2in-150ft', category: 'drywall', name: 'Mesh Tape 2 in x 150 ft', unit: 'ROLL', price: 5.75, description: 'Self-adhesive' },
  { id: 'tape-mesh-2in-300ft', category: 'drywall', name: 'Mesh Tape 2 in x 300 ft', unit: 'ROLL', price: 9.50, description: 'Self-adhesive' },
  { id: 'compound-joint-gallon', category: 'drywall', name: 'Joint Compound 1 gal', unit: 'BUCKET', price: 12.50, description: 'All-purpose' },
  { id: 'compound-joint-4-5gal', category: 'drywall', name: 'Joint Compound 4.5 gal', unit: 'BUCKET', price: 18.75, description: 'All-purpose' },
  { id: 'compound-joint-5gal', category: 'drywall', name: 'Joint Compound 5 gal', unit: 'BUCKET', price: 21.50, description: 'All-purpose' },
  { id: 'compound-lightweight-gallon', category: 'drywall', name: 'Lightweight Compound 1 gal', unit: 'BUCKET', price: 14.25, description: 'Easy sand' },
  { id: 'compound-lightweight-4-5gal', category: 'drywall', name: 'Lightweight Compound 4.5 gal', unit: 'BUCKET', price: 22.50, description: 'Easy sand' },
  { id: 'compound-topping-gallon', category: 'drywall', name: 'Topping Compound 1 gal', unit: 'BUCKET', price: 13.75, description: 'Finish coat' },
  { id: 'compound-topping-4-5gal', category: 'drywall', name: 'Topping Compound 4.5 gal', unit: 'BUCKET', price: 20.50, description: 'Finish coat' },
  { id: 'compound-20min-bag', category: 'drywall', name: 'Setting Compound 20-min (25 lb)', unit: 'BAG', price: 16.50, description: 'Hot mud' },
  { id: 'compound-45min-bag', category: 'drywall', name: 'Setting Compound 45-min (25 lb)', unit: 'BAG', price: 16.50, description: 'Hot mud' },
  { id: 'compound-90min-bag', category: 'drywall', name: 'Setting Compound 90-min (25 lb)', unit: 'BAG', price: 16.50, description: 'Hot mud' },
  { id: 'spackle-pint', category: 'drywall', name: 'Spackling Paste Pint', unit: 'TUB', price: 5.25, description: 'Small repairs' },
  { id: 'spackle-quart', category: 'drywall', name: 'Spackling Paste Quart', unit: 'TUB', price: 7.50, description: 'Small repairs' },
  { id: 'corner-bead-8ft', category: 'drywall', name: 'Corner Bead 8 ft', unit: 'EA', price: 2.75, description: 'Metal corner' },
  { id: 'corner-bead-10ft', category: 'drywall', name: 'Corner Bead 10 ft', unit: 'EA', price: 3.25, description: 'Metal corner' },
  { id: 'corner-bead-bullnose-8ft', category: 'drywall', name: 'Bullnose Corner Bead 8 ft', unit: 'EA', price: 4.50, description: 'Rounded corner' },
  { id: 'corner-bead-vinyl-8ft', category: 'drywall', name: 'Vinyl Corner Bead 8 ft', unit: 'EA', price: 3.50, description: 'Flexible' },
  { id: 'j-bead-1-2in-8ft', category: 'drywall', name: 'J-Bead 1/2 in 8 ft', unit: 'EA', price: 2.95, description: 'Edge trim' },
  { id: 'l-bead-1-2in-8ft', category: 'drywall', name: 'L-Bead 1/2 in 8 ft', unit: 'EA', price: 2.95, description: 'Edge trim' },
  { id: 'archway-bead-flex-8ft', category: 'drywall', name: 'Flexible Archway Bead 8 ft', unit: 'EA', price: 5.75, description: 'Curved corners' },
  { id: 'mud-pan-12in', category: 'drywall', name: 'Mud Pan 12 in', unit: 'EA', price: 8.50, description: 'Stainless steel' },
  { id: 'knife-taping-6in', category: 'drywall', name: 'Taping Knife 6 in', unit: 'EA', price: 12.50, description: 'Joint knife' },
  { id: 'knife-taping-10in', category: 'drywall', name: 'Taping Knife 10 in', unit: 'EA', price: 18.75, description: 'Joint knife' },
  { id: 'knife-taping-12in', category: 'drywall', name: 'Taping Knife 12 in', unit: 'EA', price: 22.50, description: 'Joint knife' },
  { id: 'hawk-12in', category: 'drywall', name: 'Drywall Hawk 12 in', unit: 'EA', price: 14.25, description: 'Aluminum' },
  { id: 'sander-pole-9in', category: 'drywall', name: 'Pole Sander 9 in', unit: 'EA', price: 18.50, description: 'With pole' },
  { id: 'sanding-screen-220', category: 'drywall', name: 'Sanding Screen 220 Grit (5)', unit: 'PACK', price: 6.75, description: 'For pole sander' },
  { id: 'sandpaper-120-sheet', category: 'drywall', name: 'Sandpaper 120 Grit (10)', unit: 'PACK', price: 4.50, description: 'Hand sanding' },
  { id: 'sandpaper-150-sheet', category: 'drywall', name: 'Sandpaper 150 Grit (10)', unit: 'PACK', price: 4.50, description: 'Hand sanding' },
  { id: 'rasp-drywall-surform', category: 'drywall', name: 'Drywall Rasp Surform', unit: 'EA', price: 12.75, description: 'Edge shaping' },
  { id: 'saw-drywall-6in', category: 'drywall', name: 'Drywall Saw 6 in', unit: 'EA', price: 8.25, description: 'Jab saw' },
  { id: 'saw-drywall-keyhole', category: 'drywall', name: 'Keyhole Saw', unit: 'EA', price: 7.50, description: 'Cutouts' },
  { id: 'circle-cutter-drywall', category: 'drywall', name: 'Circle Cutter', unit: 'EA', price: 16.50, description: 'For outlets' },
  { id: 'lifter-panel-drywall', category: 'drywall', name: 'Panel Lifter', unit: 'EA', price: 18.75, description: 'Foot lever' },

  // ============================================================================
  // ELECTRICAL (Electricians) - 60 products
  // ============================================================================
  { id: 'wire-romex-14-2-250ft', category: 'electrical', name: 'Romex 14/2 NM-B 250 ft', unit: 'ROLL', price: 95.00, description: '15A circuits' },
  { id: 'wire-romex-12-2-250ft', category: 'electrical', name: 'Romex 12/2 NM-B 250 ft', unit: 'ROLL', price: 125.00, description: '20A circuits' },
  { id: 'wire-romex-10-2-250ft', category: 'electrical', name: 'Romex 10/2 NM-B 250 ft', unit: 'ROLL', price: 215.00, description: '30A circuits' },
  { id: 'wire-romex-14-3-250ft', category: 'electrical', name: 'Romex 14/3 NM-B 250 ft', unit: 'ROLL', price: 135.00, description: '3-way switches' },
  { id: 'wire-romex-12-3-250ft', category: 'electrical', name: 'Romex 12/3 NM-B 250 ft', unit: 'ROLL', price: 175.00, description: '3-way switches' },
  { id: 'wire-romex-6-3-100ft', category: 'electrical', name: 'Romex 6/3 NM-B 100 ft', unit: 'ROLL', price: 285.00, description: '50A circuits' },
  { id: 'wire-thhn-12awg-500ft-black', category: 'electrical', name: 'THHN 12 AWG Black 500 ft', unit: 'ROLL', price: 85.00, description: 'Conduit wire' },
  { id: 'wire-thhn-12awg-500ft-white', category: 'electrical', name: 'THHN 12 AWG White 500 ft', unit: 'ROLL', price: 85.00, description: 'Conduit wire' },
  { id: 'wire-thhn-12awg-500ft-red', category: 'electrical', name: 'THHN 12 AWG Red 500 ft', unit: 'ROLL', price: 85.00, description: 'Conduit wire' },
  { id: 'wire-thhn-10awg-500ft-black', category: 'electrical', name: 'THHN 10 AWG Black 500 ft', unit: 'ROLL', price: 145.00, description: 'Conduit wire' },
  { id: 'wire-ground-6awg-250ft', category: 'electrical', name: 'Ground Wire 6 AWG 250 ft', unit: 'ROLL', price: 165.00, description: 'Bare copper' },
  { id: 'wire-ground-8awg-250ft', category: 'electrical', name: 'Ground Wire 8 AWG 250 ft', unit: 'ROLL', price: 95.00, description: 'Bare copper' },
  { id: 'conduit-emt-1-2in-10ft', category: 'electrical', name: 'EMT Conduit 1/2 in 10 ft', unit: 'EA', price: 6.75, description: 'Thin wall' },
  { id: 'conduit-emt-3-4in-10ft', category: 'electrical', name: 'EMT Conduit 3/4 in 10 ft', unit: 'EA', price: 9.25, description: 'Thin wall' },
  { id: 'conduit-emt-1in-10ft', category: 'electrical', name: 'EMT Conduit 1 in 10 ft', unit: 'EA', price: 14.50, description: 'Thin wall' },
  { id: 'conduit-pvc-1-2in-10ft', category: 'electrical', name: 'PVC Conduit 1/2 in 10 ft', unit: 'EA', price: 4.25, description: 'Schedule 40' },
  { id: 'conduit-pvc-3-4in-10ft', category: 'electrical', name: 'PVC Conduit 3/4 in 10 ft', unit: 'EA', price: 5.75, description: 'Schedule 40' },
  { id: 'conduit-pvc-1in-10ft', category: 'electrical', name: 'PVC Conduit 1 in 10 ft', unit: 'EA', price: 8.50, description: 'Schedule 40' },
  { id: 'conduit-flex-1-2in-25ft', category: 'electrical', name: 'Flexible Conduit 1/2 in 25 ft', unit: 'ROLL', price: 18.50, description: 'Liquid tight' },
  { id: 'conduit-flex-3-4in-25ft', category: 'electrical', name: 'Flexible Conduit 3/4 in 25 ft', unit: 'ROLL', price: 28.75, description: 'Liquid tight' },
  { id: 'box-outlet-1gang-plastic', category: 'electrical', name: 'Outlet Box 1-Gang Plastic', unit: 'EA', price: 0.85, description: 'New work' },
  { id: 'box-outlet-2gang-plastic', category: 'electrical', name: 'Outlet Box 2-Gang Plastic', unit: 'EA', price: 1.35, description: 'New work' },
  { id: 'box-outlet-1gang-metal', category: 'electrical', name: 'Outlet Box 1-Gang Metal', unit: 'EA', price: 1.95, description: 'Old work' },
  { id: 'box-outlet-2gang-metal', category: 'electrical', name: 'Outlet Box 2-Gang Metal', unit: 'EA', price: 2.85, description: 'Old work' },
  { id: 'box-ceiling-pancake', category: 'electrical', name: 'Pancake Ceiling Box', unit: 'EA', price: 1.75, description: '1/2 in deep' },
  { id: 'box-ceiling-round', category: 'electrical', name: 'Round Ceiling Box', unit: 'EA', price: 2.25, description: 'With bracket' },
  { id: 'box-ceiling-octagon', category: 'electrical', name: 'Octagon Ceiling Box', unit: 'EA', price: 2.50, description: 'With bracket' },
  { id: 'box-junction-4x4', category: 'electrical', name: 'Junction Box 4x4', unit: 'EA', price: 2.15, description: 'Square box' },
  { id: 'outlet-15a-white', category: 'electrical', name: 'Outlet 15A White', unit: 'EA', price: 1.25, description: 'Duplex receptacle' },
  { id: 'outlet-15a-ivory', category: 'electrical', name: 'Outlet 15A Ivory', unit: 'EA', price: 1.25, description: 'Duplex receptacle' },
  { id: 'outlet-20a-white', category: 'electrical', name: 'Outlet 20A White', unit: 'EA', price: 2.15, description: 'T-slot receptacle' },
  { id: 'outlet-gfci-15a-white', category: 'electrical', name: 'GFCI Outlet 15A White', unit: 'EA', price: 16.50, description: 'Ground fault' },
  { id: 'outlet-gfci-20a-white', category: 'electrical', name: 'GFCI Outlet 20A White', unit: 'EA', price: 19.75, description: 'Ground fault' },
  { id: 'outlet-usb-15a-white', category: 'electrical', name: 'USB Outlet 15A White', unit: 'EA', price: 18.50, description: 'With USB ports' },
  { id: 'switch-single-white', category: 'electrical', name: 'Single-Pole Switch White', unit: 'EA', price: 1.15, description: '15A switch' },
  { id: 'switch-3way-white', category: 'electrical', name: '3-Way Switch White', unit: 'EA', price: 2.25, description: '15A switch' },
  { id: 'switch-4way-white', category: 'electrical', name: '4-Way Switch White', unit: 'EA', price: 5.50, description: '15A switch' },
  { id: 'switch-dimmer-white', category: 'electrical', name: 'Dimmer Switch White', unit: 'EA', price: 14.75, description: 'LED compatible' },
  { id: 'switch-dimmer-3way-white', category: 'electrical', name: '3-Way Dimmer Switch White', unit: 'EA', price: 24.50, description: 'LED compatible' },
  { id: 'plate-1gang-white', category: 'electrical', name: 'Wall Plate 1-Gang White', unit: 'EA', price: 0.65, description: 'Standard' },
  { id: 'plate-2gang-white', category: 'electrical', name: 'Wall Plate 2-Gang White', unit: 'EA', price: 1.15, description: 'Standard' },
  { id: 'plate-3gang-white', category: 'electrical', name: 'Wall Plate 3-Gang White', unit: 'EA', price: 1.85, description: 'Standard' },
  { id: 'breaker-15a-single', category: 'electrical', name: 'Circuit Breaker 15A Single-Pole', unit: 'EA', price: 6.50, description: 'Standard breaker' },
  { id: 'breaker-20a-single', category: 'electrical', name: 'Circuit Breaker 20A Single-Pole', unit: 'EA', price: 7.25, description: 'Standard breaker' },
  { id: 'breaker-30a-double', category: 'electrical', name: 'Circuit Breaker 30A Double-Pole', unit: 'EA', price: 16.50, description: '240V breaker' },
  { id: 'breaker-40a-double', category: 'electrical', name: 'Circuit Breaker 40A Double-Pole', unit: 'EA', price: 18.75, description: '240V breaker' },
  { id: 'breaker-50a-double', category: 'electrical', name: 'Circuit Breaker 50A Double-Pole', unit: 'EA', price: 22.50, description: '240V breaker' },
  { id: 'breaker-gfci-15a', category: 'electrical', name: 'GFCI Breaker 15A', unit: 'EA', price: 48.00, description: 'Whole circuit protection' },
  { id: 'breaker-gfci-20a', category: 'electrical', name: 'GFCI Breaker 20A', unit: 'EA', price: 52.00, description: 'Whole circuit protection' },
  { id: 'breaker-afci-15a', category: 'electrical', name: 'AFCI Breaker 15A', unit: 'EA', price: 42.00, description: 'Arc fault protection' },
  { id: 'breaker-afci-20a', category: 'electrical', name: 'AFCI Breaker 20A', unit: 'EA', price: 45.00, description: 'Arc fault protection' },
  { id: 'panel-load-center-100a', category: 'electrical', name: 'Load Center 100A 20-Space', unit: 'EA', price: 125.00, description: 'Main breaker panel' },
  { id: 'panel-load-center-200a', category: 'electrical', name: 'Load Center 200A 40-Space', unit: 'EA', price: 285.00, description: 'Main breaker panel' },
  { id: 'wire-connector-red', category: 'electrical', name: 'Wire Nuts Red (100)', unit: 'BOX', price: 6.50, description: '18-10 AWG' },
  { id: 'wire-connector-yellow', category: 'electrical', name: 'Wire Nuts Yellow (100)', unit: 'BOX', price: 7.25, description: '14-12 AWG' },
  { id: 'wire-connector-orange', category: 'electrical', name: 'Wire Nuts Orange (100)', unit: 'BOX', price: 5.75, description: '18-14 AWG' },
  { id: 'tape-electrical-black', category: 'electrical', name: 'Electrical Tape Black', unit: 'ROLL', price: 2.25, description: '3/4 in x 60 ft' },
  { id: 'tape-electrical-color-pack', category: 'electrical', name: 'Electrical Tape Color Pack (10)', unit: 'PACK', price: 18.50, description: 'Phase marking' },
  { id: 'staple-cable-romex-1-2in', category: 'electrical', name: 'Cable Staples 1/2 in (100)', unit: 'BOX', price: 5.25, description: 'Romex staples' },

  // ============================================================================
  // PLUMBING (Plumbers) - 60 products
  // ============================================================================
  { id: 'pipe-pex-1-2in-100ft-red', category: 'plumbing', name: 'PEX Pipe 1/2 in 100 ft Red', unit: 'ROLL', price: 48.00, description: 'Hot water' },
  { id: 'pipe-pex-1-2in-100ft-blue', category: 'plumbing', name: 'PEX Pipe 1/2 in 100 ft Blue', unit: 'ROLL', price: 48.00, description: 'Cold water' },
  { id: 'pipe-pex-3-4in-100ft-red', category: 'plumbing', name: 'PEX Pipe 3/4 in 100 ft Red', unit: 'ROLL', price: 78.00, description: 'Hot water' },
  { id: 'pipe-pex-3-4in-100ft-blue', category: 'plumbing', name: 'PEX Pipe 3/4 in 100 ft Blue', unit: 'ROLL', price: 78.00, description: 'Cold water' },
  { id: 'pipe-pex-1in-100ft', category: 'plumbing', name: 'PEX Pipe 1 in 100 ft', unit: 'ROLL', price: 125.00, description: 'Main line' },
  { id: 'pipe-cpvc-1-2in-10ft', category: 'plumbing', name: 'CPVC Pipe 1/2 in 10 ft', unit: 'EA', price: 4.25, description: 'Hot/cold water' },
  { id: 'pipe-cpvc-3-4in-10ft', category: 'plumbing', name: 'CPVC Pipe 3/4 in 10 ft', unit: 'EA', price: 6.50, description: 'Hot/cold water' },
  { id: 'pipe-cpvc-1in-10ft', category: 'plumbing', name: 'CPVC Pipe 1 in 10 ft', unit: 'EA', price: 9.75, description: 'Hot/cold water' },
  { id: 'pipe-pvc-sch40-1-5in-10ft', category: 'plumbing', name: 'PVC Pipe Sch 40 1-1/2 in 10 ft', unit: 'EA', price: 5.75, description: 'Drain pipe' },
  { id: 'pipe-pvc-sch40-2in-10ft', category: 'plumbing', name: 'PVC Pipe Sch 40 2 in 10 ft', unit: 'EA', price: 7.50, description: 'Drain pipe' },
  { id: 'pipe-pvc-sch40-3in-10ft', category: 'plumbing', name: 'PVC Pipe Sch 40 3 in 10 ft', unit: 'EA', price: 12.50, description: 'Drain pipe' },
  { id: 'pipe-pvc-sch40-4in-10ft', category: 'plumbing', name: 'PVC Pipe Sch 40 4 in 10 ft', unit: 'EA', price: 18.75, description: 'Main drain' },
  { id: 'pipe-abs-1-5in-10ft', category: 'plumbing', name: 'ABS Pipe 1-1/2 in 10 ft', unit: 'EA', price: 6.25, description: 'Drain pipe' },
  { id: 'pipe-abs-2in-10ft', category: 'plumbing', name: 'ABS Pipe 2 in 10 ft', unit: 'EA', price: 8.50, description: 'Drain pipe' },
  { id: 'pipe-abs-3in-10ft', category: 'plumbing', name: 'ABS Pipe 3 in 10 ft', unit: 'EA', price: 14.25, description: 'Drain pipe' },
  { id: 'pipe-abs-4in-10ft', category: 'plumbing', name: 'ABS Pipe 4 in 10 ft', unit: 'EA', price: 21.50, description: 'Main drain' },
  { id: 'pipe-copper-1-2in-10ft', category: 'plumbing', name: 'Copper Pipe Type L 1/2 in 10 ft', unit: 'EA', price: 28.50, description: 'Water supply' },
  { id: 'pipe-copper-3-4in-10ft', category: 'plumbing', name: 'Copper Pipe Type L 3/4 in 10 ft', unit: 'EA', price: 42.00, description: 'Water supply' },
  { id: 'fitting-pex-elbow-1-2in', category: 'plumbing', name: 'PEX Elbow 1/2 in (10)', unit: 'PACK', price: 8.50, description: '90 degree' },
  { id: 'fitting-pex-tee-1-2in', category: 'plumbing', name: 'PEX Tee 1/2 in (10)', unit: 'PACK', price: 9.75, description: 'Branch fitting' },
  { id: 'fitting-pex-coupling-1-2in', category: 'plumbing', name: 'PEX Coupling 1/2 in (10)', unit: 'PACK', price: 7.50, description: 'Join pipes' },
  { id: 'fitting-cpvc-elbow-1-2in', category: 'plumbing', name: 'CPVC Elbow 1/2 in', unit: 'EA', price: 0.65, description: '90 degree' },
  { id: 'fitting-cpvc-tee-1-2in', category: 'plumbing', name: 'CPVC Tee 1/2 in', unit: 'EA', price: 0.85, description: 'Branch fitting' },
  { id: 'fitting-cpvc-coupling-1-2in', category: 'plumbing', name: 'CPVC Coupling 1/2 in', unit: 'EA', price: 0.45, description: 'Join pipes' },
  { id: 'fitting-pvc-elbow-2in', category: 'plumbing', name: 'PVC Elbow 2 in 90°', unit: 'EA', price: 1.85, description: 'Drain fitting' },
  { id: 'fitting-pvc-tee-2in', category: 'plumbing', name: 'PVC Tee 2 in', unit: 'EA', price: 2.25, description: 'Drain fitting' },
  { id: 'fitting-pvc-coupling-2in', category: 'plumbing', name: 'PVC Coupling 2 in', unit: 'EA', price: 1.25, description: 'Join pipes' },
  { id: 'fitting-pvc-wye-2in', category: 'plumbing', name: 'PVC Wye 2 in', unit: 'EA', price: 2.75, description: '45° branch' },
  { id: 'fitting-pvc-combo-2in', category: 'plumbing', name: 'PVC Combo 2 in', unit: 'EA', price: 3.50, description: 'Wye + 1/8 bend' },
  { id: 'fitting-pvc-elbow-3in', category: 'plumbing', name: 'PVC Elbow 3 in 90°', unit: 'EA', price: 3.75, description: 'Drain fitting' },
  { id: 'fitting-pvc-wye-3in', category: 'plumbing', name: 'PVC Wye 3 in', unit: 'EA', price: 5.25, description: '45° branch' },
  { id: 'fitting-pvc-elbow-4in', category: 'plumbing', name: 'PVC Elbow 4 in 90°', unit: 'EA', price: 6.50, description: 'Main drain' },
  { id: 'fitting-pvc-wye-4in', category: 'plumbing', name: 'PVC Wye 4 in', unit: 'EA', price: 8.75, description: 'Main drain branch' },
  { id: 'valve-ball-1-2in-pex', category: 'plumbing', name: 'Ball Valve 1/2 in PEX', unit: 'EA', price: 8.50, description: 'Shut-off valve' },
  { id: 'valve-ball-3-4in-pex', category: 'plumbing', name: 'Ball Valve 3/4 in PEX', unit: 'EA', price: 12.75, description: 'Shut-off valve' },
  { id: 'valve-ball-1-2in-cpvc', category: 'plumbing', name: 'Ball Valve 1/2 in CPVC', unit: 'EA', price: 6.25, description: 'Shut-off valve' },
  { id: 'valve-gate-1-2in', category: 'plumbing', name: 'Gate Valve 1/2 in', unit: 'EA', price: 9.50, description: 'Full port' },
  { id: 'valve-stop-1-2in-quarter-turn', category: 'plumbing', name: 'Stop Valve 1/2 in Quarter Turn', unit: 'EA', price: 7.25, description: 'Angle stop' },
  { id: 'valve-stop-1-2in-compression', category: 'plumbing', name: 'Stop Valve 1/2 in Compression', unit: 'EA', price: 5.75, description: 'Angle stop' },
  { id: 'faucet-kitchen-single-handle', category: 'plumbing', name: 'Kitchen Faucet Single-Handle', unit: 'EA', price: 78.00, description: 'With sprayer' },
  { id: 'faucet-kitchen-pulldown', category: 'plumbing', name: 'Kitchen Faucet Pull-Down', unit: 'EA', price: 125.00, description: 'Modern style' },
  { id: 'faucet-bathroom-4in-center', category: 'plumbing', name: 'Bathroom Faucet 4 in Center', unit: 'EA', price: 42.00, description: '2-handle' },
  { id: 'faucet-bathroom-8in-widespread', category: 'plumbing', name: 'Bathroom Faucet 8 in Widespread', unit: 'EA', price: 85.00, description: '3-piece' },
  { id: 'faucet-laundry-utility', category: 'plumbing', name: 'Laundry/Utility Faucet', unit: 'EA', price: 32.00, description: 'Wall mount' },
  { id: 'toilet-2piece-standard', category: 'plumbing', name: 'Toilet 2-Piece Standard', unit: 'EA', price: 185.00, description: '1.6 GPF' },
  { id: 'toilet-2piece-comfort-height', category: 'plumbing', name: 'Toilet 2-Piece Comfort Height', unit: 'EA', price: 225.00, description: 'ADA height' },
  { id: 'toilet-1piece', category: 'plumbing', name: 'Toilet 1-Piece', unit: 'EA', price: 385.00, description: 'Modern style' },
  { id: 'toilet-wax-ring', category: 'plumbing', name: 'Toilet Wax Ring with Flange', unit: 'EA', price: 4.25, description: 'Seal' },
  { id: 'toilet-bolts-brass', category: 'plumbing', name: 'Toilet Bolts Brass (2)', unit: 'PACK', price: 3.75, description: 'Closet bolts' },
  { id: 'toilet-supply-line-12in', category: 'plumbing', name: 'Toilet Supply Line 12 in', unit: 'EA', price: 6.50, description: 'Braided stainless' },
  { id: 'sink-vanity-undermount', category: 'plumbing', name: 'Vanity Sink Undermount', unit: 'EA', price: 95.00, description: 'Oval white' },
  { id: 'sink-vanity-dropin', category: 'plumbing', name: 'Vanity Sink Drop-In', unit: 'EA', price: 68.00, description: 'Oval white' },
  { id: 'sink-kitchen-single-bowl', category: 'plumbing', name: 'Kitchen Sink Single Bowl', unit: 'EA', price: 125.00, description: 'Stainless steel' },
  { id: 'sink-kitchen-double-bowl', category: 'plumbing', name: 'Kitchen Sink Double Bowl', unit: 'EA', price: 165.00, description: 'Stainless steel' },
  { id: 'sink-laundry-utility', category: 'plumbing', name: 'Laundry/Utility Sink', unit: 'EA', price: 78.00, description: 'Plastic tub' },
  { id: 'drain-popup-chrome', category: 'plumbing', name: 'Pop-Up Drain Chrome', unit: 'EA', price: 14.50, description: 'Bathroom sink' },
  { id: 'drain-grid-chrome', category: 'plumbing', name: 'Grid Drain Chrome', unit: 'EA', price: 12.75, description: 'Bathroom sink' },
  { id: 'drain-basket-strainer', category: 'plumbing', name: 'Basket Strainer', unit: 'EA', price: 16.50, description: 'Kitchen sink' },
  { id: 'pputty-plumbers-14oz', category: 'plumbing', name: 'Plumbers Putty 14 oz', unit: 'TUB', price: 4.25, description: 'Sealing' },

  // ============================================================================
  // ROOFING (Roofers) - 50 products
  // ============================================================================
  { id: 'shingles-3tab-bundle', category: 'roofing', name: '3-Tab Shingles Bundle', unit: 'BUNDLE', price: 32.50, description: '33.3 SF coverage' },
  { id: 'shingles-architectural-bundle', category: 'roofing', name: 'Architectural Shingles Bundle', unit: 'BUNDLE', price: 42.00, description: '33.3 SF coverage' },
  { id: 'shingles-designer-bundle', category: 'roofing', name: 'Designer Shingles Bundle', unit: 'BUNDLE', price: 58.00, description: '33.3 SF coverage' },
  { id: 'shingles-impact-resistant-bundle', category: 'roofing', name: 'Impact-Resistant Shingles Bundle', unit: 'BUNDLE', price: 68.00, description: 'Class 4 rated' },
  { id: 'shingles-starter-strip-100ft', category: 'roofing', name: 'Starter Strip Shingles 100 ft', unit: 'ROLL', price: 38.50, description: 'Eave protection' },
  { id: 'shingles-ridge-cap-bundle', category: 'roofing', name: 'Ridge Cap Shingles Bundle', unit: 'BUNDLE', price: 52.00, description: '20 LF coverage' },
  { id: 'underlayment-felt-15lb-432sf', category: 'roofing', name: 'Felt Underlayment 15 lb 432 SF', unit: 'ROLL', price: 24.50, description: 'Roofing felt' },
  { id: 'underlayment-felt-30lb-216sf', category: 'roofing', name: 'Felt Underlayment 30 lb 216 SF', unit: 'ROLL', price: 28.75, description: 'Heavy duty' },
  { id: 'underlayment-synthetic-1000sf', category: 'roofing', name: 'Synthetic Underlayment 1000 SF', unit: 'ROLL', price: 125.00, description: 'Lightweight' },
  { id: 'underlayment-ice-water-200sf', category: 'roofing', name: 'Ice & Water Shield 200 SF', unit: 'ROLL', price: 95.00, description: 'Self-adhering' },
  { id: 'underlayment-ice-water-65sf', category: 'roofing', name: 'Ice & Water Shield 65 SF', unit: 'ROLL', price: 38.00, description: 'Self-adhering' },
  { id: 'drip-edge-aluminum-10ft', category: 'roofing', name: 'Drip Edge Aluminum 10 ft', unit: 'EA', price: 8.50, description: 'Eave protection' },
  { id: 'drip-edge-galvanized-10ft', category: 'roofing', name: 'Drip Edge Galvanized 10 ft', unit: 'EA', price: 6.75, description: 'Eave protection' },
  { id: 'flashing-step-8in', category: 'roofing', name: 'Step Flashing 8 in (100)', unit: 'BUNDLE', price: 68.00, description: 'Galvanized' },
  { id: 'flashing-valley-10ft', category: 'roofing', name: 'Valley Flashing 10 ft', unit: 'EA', price: 18.50, description: 'W-style' },
  { id: 'flashing-counter-8in-10ft', category: 'roofing', name: 'Counter Flashing 8 in 10 ft', unit: 'EA', price: 22.50, description: 'Chimney flashing' },
  { id: 'flashing-pipe-boot-1-5-3in', category: 'roofing', name: 'Pipe Boot Flashing 1-1/2 to 3 in', unit: 'EA', price: 14.75, description: 'EPDM rubber' },
  { id: 'flashing-pipe-boot-3-4in', category: 'roofing', name: 'Pipe Boot Flashing 3 to 4 in', unit: 'EA', price: 16.50, description: 'EPDM rubber' },
  { id: 'flashing-roof-jack-3in', category: 'roofing', name: 'Roof Jack Flashing 3 in', unit: 'EA', price: 24.50, description: 'Vent pipe' },
  { id: 'vent-ridge-4ft', category: 'roofing', name: 'Ridge Vent 4 ft', unit: 'EA', price: 12.75, description: 'Shingle-over style' },
  { id: 'vent-ridge-roll-20ft', category: 'roofing', name: 'Ridge Vent Roll 20 ft', unit: 'ROLL', price: 48.00, description: 'Continuous vent' },
  { id: 'vent-roof-static-square', category: 'roofing', name: 'Static Roof Vent Square', unit: 'EA', price: 18.50, description: 'Aluminum' },
  { id: 'vent-roof-turbine', category: 'roofing', name: 'Turbine Roof Vent 12 in', unit: 'EA', price: 42.00, description: 'Wind powered' },
  { id: 'vent-soffit-8x16', category: 'roofing', name: 'Soffit Vent 8x16 in', unit: 'EA', price: 4.25, description: 'Aluminum' },
  { id: 'vent-gable-18in', category: 'roofing', name: 'Gable Vent 18 in Round', unit: 'EA', price: 22.50, description: 'Aluminum' },
  { id: 'cement-roof-1gal', category: 'roofing', name: 'Roof Cement 1 gal', unit: 'BUCKET', price: 12.50, description: 'Plastic cement' },
  { id: 'cement-roof-5gal', category: 'roofing', name: 'Roof Cement 5 gal', unit: 'BUCKET', price: 48.00, description: 'Plastic cement' },
  { id: 'cement-asphalt-10oz', category: 'roofing', name: 'Asphalt Roof Cement 10 oz', unit: 'TUBE', price: 5.75, description: 'For caulk gun' },
  { id: 'sealant-lap-10oz', category: 'roofing', name: 'Lap Sealant 10 oz', unit: 'TUBE', price: 6.50, description: 'Rubberized' },
  { id: 'sealant-shingle-repair-10oz', category: 'roofing', name: 'Shingle Repair Sealant 10 oz', unit: 'TUBE', price: 7.25, description: 'Color matched' },
  { id: 'tape-butyl-seal-50ft', category: 'roofing', name: 'Butyl Seal Tape 50 ft', unit: 'ROLL', price: 14.50, description: 'Self-adhering' },
  { id: 'nails-roofing-coil-7200', category: 'roofing', name: 'Roofing Coil Nails 1-1/4 in (7200)', unit: 'BOX', price: 68.00, description: 'For nailer' },
  { id: 'nails-roofing-cap-plastic', category: 'roofing', name: 'Cap Nails Plastic 1 in (1000)', unit: 'BOX', price: 24.50, description: 'Felt attachment' },
  { id: 'nails-roofing-cap-metal', category: 'roofing', name: 'Cap Nails Metal 1 in (1000)', unit: 'BOX', price: 32.00, description: 'Felt attachment' },
  { id: 'screws-metal-roof-1-5in', category: 'roofing', name: 'Metal Roof Screws 1-1/2 in (250)', unit: 'BOX', price: 28.50, description: 'Hex head with washer' },
  { id: 'screws-metal-roof-2-5in', category: 'roofing', name: 'Metal Roof Screws 2-1/2 in (250)', unit: 'BOX', price: 32.00, description: 'Hex head with washer' },
  { id: 'panel-metal-roof-3ft-ribbed', category: 'roofing', name: 'Metal Roof Panel 3 ft Ribbed', unit: 'SHEET', price: 42.00, description: 'Galvanized' },
  { id: 'panel-metal-roof-3ft-corrugated', category: 'roofing', name: 'Metal Roof Panel 3 ft Corrugated', unit: 'SHEET', price: 38.00, description: 'Galvanized' },
  { id: 'closure-strip-foam-3ft', category: 'roofing', name: 'Foam Closure Strip 3 ft', unit: 'EA', price: 4.25, description: 'For metal roof' },
  { id: 'ridge-cap-metal-10ft', category: 'roofing', name: 'Metal Ridge Cap 10 ft', unit: 'EA', price: 24.50, description: 'Matching metal' },
  { id: 'gutter-aluminum-5in-10ft', category: 'roofing', name: 'Aluminum Gutter 5 in 10 ft', unit: 'EA', price: 12.75, description: 'K-style' },
  { id: 'downspout-aluminum-3x4-10ft', category: 'roofing', name: 'Aluminum Downspout 3x4 in 10 ft', unit: 'EA', price: 14.50, description: 'Rectangular' },
  { id: 'elbow-downspout-3x4-style-a', category: 'roofing', name: 'Downspout Elbow 3x4 in Style A', unit: 'EA', price: 5.75, description: 'Top/bottom' },
  { id: 'elbow-downspout-3x4-style-b', category: 'roofing', name: 'Downspout Elbow 3x4 in Style B', unit: 'EA', price: 5.75, description: 'Side' },
  { id: 'hanger-gutter-hidden', category: 'roofing', name: 'Hidden Gutter Hanger (10)', unit: 'PACK', price: 18.50, description: 'Heavy duty' },
  { id: 'bracket-gutter-spike-ferrule', category: 'roofing', name: 'Gutter Spike & Ferrule (10)', unit: 'PACK', price: 12.50, description: 'Traditional' },
  { id: 'guard-gutter-screen-3ft', category: 'roofing', name: 'Gutter Guard Screen 3 ft', unit: 'EA', price: 8.50, description: 'Aluminum mesh' },
  { id: 'sealant-gutter-10oz', category: 'roofing', name: 'Gutter Sealant 10 oz', unit: 'TUBE', price: 6.25, description: 'Waterproof' },
  { id: 'end-cap-gutter-left', category: 'roofing', name: 'Gutter End Cap Left', unit: 'EA', price: 3.75, description: 'Aluminum' },
  { id: 'end-cap-gutter-right', category: 'roofing', name: 'Gutter End Cap Right', unit: 'EA', price: 3.75, description: 'Aluminum' },

  // ============================================================================
  // MASONRY (Masonry contractors) - 50 products
  // ============================================================================
  { id: 'block-concrete-8x8x16-standard', category: 'masonry', name: 'Concrete Block 8x8x16 Standard', unit: 'EA', price: 2.85, description: '2-core hollow' },
  { id: 'block-concrete-8x8x16-solid', category: 'masonry', name: 'Concrete Block 8x8x16 Solid', unit: 'EA', price: 4.25, description: 'Full block' },
  { id: 'block-concrete-6x8x16', category: 'masonry', name: 'Concrete Block 6x8x16', unit: 'EA', price: 2.45, description: '2-core hollow' },
  { id: 'block-concrete-4x8x16', category: 'masonry', name: 'Concrete Block 4x8x16', unit: 'EA', price: 2.15, description: '2-core hollow' },
  { id: 'block-concrete-12x8x16', category: 'masonry', name: 'Concrete Block 12x8x16', unit: 'EA', price: 4.85, description: '2-core hollow' },
  { id: 'block-concrete-half-8x8x8', category: 'masonry', name: 'Half Block 8x8x8', unit: 'EA', price: 1.85, description: 'Half height' },
  { id: 'block-concrete-corner-8x8x16', category: 'masonry', name: 'Corner Block 8x8x16', unit: 'EA', price: 3.25, description: 'Single corner open' },
  { id: 'block-concrete-cap-solid-8x8x16', category: 'masonry', name: 'Cap Block Solid 8x8x16', unit: 'EA', price: 5.50, description: 'Top course' },
  { id: 'brick-common-red', category: 'masonry', name: 'Common Red Brick', unit: 'EA', price: 0.85, description: 'Standard modular' },
  { id: 'brick-face-red', category: 'masonry', name: 'Face Brick Red', unit: 'EA', price: 1.45, description: 'Finished face' },
  { id: 'brick-face-brown', category: 'masonry', name: 'Face Brick Brown', unit: 'EA', price: 1.45, description: 'Finished face' },
  { id: 'brick-face-gray', category: 'masonry', name: 'Face Brick Gray', unit: 'EA', price: 1.45, description: 'Finished face' },
  { id: 'brick-fire-9x4-5', category: 'masonry', name: 'Fire Brick 9x4.5 in', unit: 'EA', price: 3.85, description: 'High temp rated' },
  { id: 'brick-paver-red-4x8', category: 'masonry', name: 'Paver Brick Red 4x8 in', unit: 'EA', price: 1.25, description: 'Outdoor paving' },
  { id: 'cement-portland-type1-94lb', category: 'masonry', name: 'Portland Cement Type I 94 lb', unit: 'BAG', price: 14.50, description: 'General purpose' },
  { id: 'cement-masonry-type-n-80lb', category: 'masonry', name: 'Masonry Cement Type N 80 lb', unit: 'BAG', price: 12.75, description: 'Mortar mix base' },
  { id: 'cement-masonry-type-s-80lb', category: 'masonry', name: 'Masonry Cement Type S 80 lb', unit: 'BAG', price: 13.50, description: 'High strength' },
  { id: 'mortar-mix-60lb', category: 'masonry', name: 'Mortar Mix 60 lb', unit: 'BAG', price: 8.75, description: 'Just add water' },
  { id: 'mortar-mix-80lb', category: 'masonry', name: 'Mortar Mix 80 lb', unit: 'BAG', price: 10.50, description: 'Just add water' },
  { id: 'concrete-mix-60lb', category: 'masonry', name: 'Concrete Mix 60 lb', unit: 'BAG', price: 5.75, description: 'All-purpose' },
  { id: 'concrete-mix-80lb', category: 'masonry', name: 'Concrete Mix 80 lb', unit: 'BAG', price: 6.50, description: 'All-purpose' },
  { id: 'concrete-mix-fast-set-50lb', category: 'masonry', name: 'Fast-Set Concrete Mix 50 lb', unit: 'BAG', price: 9.25, description: 'Sets in 20 min' },
  { id: 'concrete-crack-filler-10lb', category: 'masonry', name: 'Concrete Crack Filler 10 lb', unit: 'BAG', price: 12.50, description: 'Vinyl patching' },
  { id: 'concrete-anchoring-50lb', category: 'masonry', name: 'Anchoring Cement 50 lb', unit: 'BAG', price: 18.75, description: 'Non-shrink' },
  { id: 'sand-masonry-50lb', category: 'masonry', name: 'Masonry Sand 50 lb', unit: 'BAG', price: 4.25, description: 'Fine sand' },
  { id: 'sand-concrete-60lb', category: 'masonry', name: 'Concrete Sand 60 lb', unit: 'BAG', price: 4.75, description: 'Coarse sand' },
  { id: 'gravel-pea-50lb', category: 'masonry', name: 'Pea Gravel 50 lb', unit: 'BAG', price: 5.50, description: '3/8 in stone' },
  { id: 'gravel-drainage-50lb', category: 'masonry', name: 'Drainage Gravel 50 lb', unit: 'BAG', price: 6.25, description: '3/4 in stone' },
  { id: 'rebar-3-8in-20ft', category: 'masonry', name: 'Rebar 3/8 in 20 ft', unit: 'EA', price: 12.50, description: 'Grade 40' },
  { id: 'rebar-1-2in-20ft', category: 'masonry', name: 'Rebar 1/2 in 20 ft', unit: 'EA', price: 18.75, description: 'Grade 60' },
  { id: 'rebar-5-8in-20ft', category: 'masonry', name: 'Rebar 5/8 in 20 ft', unit: 'EA', price: 28.50, description: 'Grade 60' },
  { id: 'rebar-chair-3in', category: 'masonry', name: 'Rebar Chair 3 in (50)', unit: 'PACK', price: 18.50, description: 'Plastic support' },
  { id: 'rebar-tie-wire-16ga', category: 'masonry', name: 'Rebar Tie Wire 16ga', unit: 'ROLL', price: 12.75, description: 'Annealed' },
  { id: 'mesh-wire-6x6-w1-4', category: 'masonry', name: 'Wire Mesh 6x6 W1.4xW1.4', unit: 'SHEET', price: 38.00, description: '5x10 sheet' },
  { id: 'mesh-wire-4x4-w2-9', category: 'masonry', name: 'Wire Mesh 4x4 W2.9xW2.9', unit: 'SHEET', price: 52.00, description: '5x10 sheet' },
  { id: 'fiber-concrete-synthetic', category: 'masonry', name: 'Synthetic Concrete Fiber 1 lb', unit: 'BAG', price: 14.50, description: 'Crack control' },
  { id: 'admix-accelerator-1gal', category: 'masonry', name: 'Concrete Accelerator 1 gal', unit: 'JUG', price: 24.50, description: 'Fast set' },
  { id: 'admix-water-reducer-1gal', category: 'masonry', name: 'Water Reducer 1 gal', unit: 'JUG', price: 22.00, description: 'Plasticizer' },
  { id: 'sealer-concrete-1gal', category: 'masonry', name: 'Concrete Sealer 1 gal', unit: 'JUG', price: 32.00, description: 'Acrylic' },
  { id: 'sealer-concrete-5gal', category: 'masonry', name: 'Concrete Sealer 5 gal', unit: 'BUCKET', price: 128.00, description: 'Acrylic' },
  { id: 'curing-compound-5gal', category: 'masonry', name: 'Curing Compound 5 gal', unit: 'BUCKET', price: 95.00, description: 'Moisture retention' },
  { id: 'bonding-agent-concrete-1gal', category: 'masonry', name: 'Concrete Bonding Agent 1 gal', unit: 'JUG', price: 28.50, description: 'Latex' },
  { id: 'form-release-agent-1gal', category: 'masonry', name: 'Form Release Agent 1 gal', unit: 'JUG', price: 18.75, description: 'Non-staining' },
  { id: 'trowel-brick-10in', category: 'masonry', name: 'Brick Trowel 10 in', unit: 'EA', price: 24.50, description: 'Philadelphia pattern' },
  { id: 'trowel-margin-5in', category: 'masonry', name: 'Margin Trowel 5 in', unit: 'EA', price: 12.75, description: 'Narrow blade' },
  { id: 'jointer-convex-3-4in', category: 'masonry', name: 'Convex Jointer 3/4 in', unit: 'EA', price: 8.50, description: 'Rounded joints' },
  { id: 'jointer-v-shape-3-4in', category: 'masonry', name: 'V-Shape Jointer 3/4 in', unit: 'EA', price: 8.50, description: 'V-joints' },
  { id: 'brush-masonry-soft', category: 'masonry', name: 'Soft Masonry Brush', unit: 'EA', price: 6.75, description: 'Cleaning' },
  { id: 'chisel-brick-wide', category: 'masonry', name: 'Wide Brick Chisel 4 in', unit: 'EA', price: 14.50, description: 'Splitting bricks' },
  { id: 'line-mason-500ft', category: 'masonry', name: 'Mason Line 500 ft', unit: 'ROLL', price: 12.50, description: 'Nylon string' },
];

// Generate SQL INSERT statements
const sqlStatements: string[] = [];

// Group by category for better organization
const categories = Array.from(new Set(products.map(p => p.category)));

for (const category of categories) {
  const categoryProducts = products.filter(p => p.category === category);

  sqlStatements.push(`-- ${category.toUpperCase()} (${categoryProducts.length} products)`);

  for (const p of categoryProducts) {
    const escapedName = p.name.replace(/'/g, "''");
    const escapedDesc = p.description.replace(/'/g, "''");
    sqlStatements.push(
      `INSERT INTO products (id, category_id, name, unit, unit_price, data_source, description) VALUES ('${p.id}', '${p.category}', '${escapedName}', '${p.unit}', ${p.price}, 'ai_estimated', '${escapedDesc}') ON CONFLICT (id) DO NOTHING;`
    );
  }

  sqlStatements.push(''); // blank line between categories
}

// Output SQL
console.log('-- ============================================================================');
console.log('-- AI-GENERATED PRODUCT CATALOG');
console.log(`-- Generated: ${new Date().toISOString()}`);
console.log(`-- Total Products: ${products.length}`);
console.log('-- Data Source: ai_estimated (2025 market research)');
console.log('-- ============================================================================');
console.log('');
console.log(sqlStatements.join('\n'));
console.log('');
console.log(`-- Successfully generated ${products.length} products across ${categories.length} categories`);
