// app/components/seed-catalog.ts (or inline in MaterialsPicker.tsx)
export type MaterialItem = {
  productId: string;
  name: string;
  unit: string; // ea | box | roll | sheet | bag | ft | gal | sq | len | pair | set
  unitPrice: number; // placeholder estimates; update per vendor
  qty?: number;
  category?: string; // used by your CategoryChips
};

/** ========== GENERAL CONTRACTOR ========== */
export const GC_CATALOG: MaterialItem[] = [
  // LUMBER & FRAMING
  {
    productId: "lumber-2x4-stud",
    name: '2"x4" Stud SPF',
    unit: "ea",
    unitPrice: 3.25,
    category: "Lumber",
  },
  {
    productId: "lumber-2x6-stud",
    name: '2"x6" Stud SPF',
    unit: "ea",
    unitPrice: 5.35,
    category: "Lumber",
  },
  {
    productId: "lumber-2x8-8",
    name: '2"x8"x8\'',
    unit: "ea",
    unitPrice: 10.9,
    category: "Lumber",
  },
  {
    productId: "lumber-2x10-12",
    name: '2"x10"x12\'',
    unit: "ea",
    unitPrice: 23.5,
    category: "Lumber",
  },
  {
    productId: "lumber-4x4-8",
    name: '4"x4"x8\' PT',
    unit: "ea",
    unitPrice: 14.5,
    category: "Lumber",
  },
  {
    productId: "ply-osb-7-16",
    name: 'OSB 7/16" 4x8',
    unit: "sheet",
    unitPrice: 12.8,
    category: "Lumber",
  },
  {
    productId: "ply-cdx-1-2",
    name: 'CDX Ply 1/2" 4x8',
    unit: "sheet",
    unitPrice: 29.0,
    category: "Lumber",
  },
  {
    productId: "ply-advantech-3-4",
    name: 'Subfloor 3/4" T&G',
    unit: "sheet",
    unitPrice: 48.0,
    category: "Lumber",
  },
  {
    productId: "engineered-lvl-1-75x11-875",
    name: 'LVL 1-3/4" x 11-7/8"',
    unit: "ft",
    unitPrice: 7.5,
    category: "Lumber",
  },
  {
    productId: "hangers-joist-lus210",
    name: "Joist Hanger LUS210",
    unit: "ea",
    unitPrice: 2.35,
    category: "Hardware",
  },
  {
    productId: "anchor-bolt-1-2x10",
    name: 'Anchor Bolt 1/2"x10"',
    unit: "ea",
    unitPrice: 2.15,
    category: "Hardware",
  },
  {
    productId: "sill-seal-3-1-2x50",
    name: "Sill Seal 3-1/2\" x 50'",
    unit: "roll",
    unitPrice: 12.0,
    category: "Insulation",
  },

  // FASTENERS & ADHESIVES
  {
    productId: "screws-drywall-1-1-4",
    name: 'Drywall Screws 1-1/4" (5k)',
    unit: "box",
    unitPrice: 38.0,
    category: "Fasteners",
  },
  {
    productId: "screws-wood-3",
    name: 'Wood Screws #9 x 3" (1k)',
    unit: "box",
    unitPrice: 79.0,
    category: "Fasteners",
  },
  {
    productId: "nails-framing-21deg",
    name: 'Framing Nails 21° (2–3/8"–3-1/4")',
    unit: "box",
    unitPrice: 54.0,
    category: "Fasteners",
  },
  {
    productId: "adhesive-construction",
    name: "Construction Adhesive (10oz)",
    unit: "ea",
    unitPrice: 4.5,
    category: "Adhesives/Sealants",
  },
  {
    productId: "pl-premium-28oz",
    name: "PL Premium (28oz)",
    unit: "ea",
    unitPrice: 11.0,
    category: "Adhesives/Sealants",
  },
  {
    productId: "silicone-100",
    name: "Silicone Sealant 100% (clear)",
    unit: "ea",
    unitPrice: 6.25,
    category: "Adhesives/Sealants",
  },
  {
    productId: "foam-gap-filler",
    name: "Expanding Foam Gap Filler",
    unit: "ea",
    unitPrice: 5.9,
    category: "Adhesives/Sealants",
  },

  // DRYWALL & FINISH
  {
    productId: "drywall-1-2-4x8",
    name: 'Drywall 1/2" 4x8',
    unit: "sheet",
    unitPrice: 13.5,
    category: "Drywall",
  },
  {
    productId: "drywall-5-8-4x12",
    name: 'Type X 5/8" 4x12',
    unit: "sheet",
    unitPrice: 23.0,
    category: "Drywall",
  },
  {
    productId: "mud-all-purpose-5gal",
    name: "Joint Compound 5 gal",
    unit: "ea",
    unitPrice: 22.0,
    category: "Drywall",
  },
  {
    productId: "tape-paper-250ft",
    name: "Drywall Paper Tape 250ft",
    unit: "roll",
    unitPrice: 3.2,
    category: "Drywall",
  },
  {
    productId: "corner-bead-metal-8ft",
    name: "Metal Corner Bead 8ft",
    unit: "ea",
    unitPrice: 2.1,
    category: "Drywall",
  },
  {
    productId: "sanding-sponge-med",
    name: "Sanding Sponge (med)",
    unit: "ea",
    unitPrice: 2.2,
    category: "Drywall",
  },

  // INSULATION & AIR SEAL
  {
    productId: "batt-r13-15-25",
    name: 'Fiberglass Batt R-13 (15"x93")',
    unit: "bag",
    unitPrice: 37.0,
    category: "Insulation",
  },
  {
    productId: "batt-r19-15-25",
    name: 'Fiberglass Batt R-19 (15"x93")',
    unit: "bag",
    unitPrice: 44.0,
    category: "Insulation",
  },
  {
    productId: "rockwool-r15-16-oc",
    name: 'Rockwool R-15 (16" o.c.)',
    unit: "bag",
    unitPrice: 65.0,
    category: "Insulation",
  },
  {
    productId: "spray-foam-kit-small",
    name: "Closed-Cell Foam Kit (Small)",
    unit: "set",
    unitPrice: 365.0,
    category: "Insulation",
  },
  {
    productId: "housewrap-9x150",
    name: "Housewrap 9' x 150'",
    unit: "roll",
    unitPrice: 129.0,
    category: "Insulation",
  },
  {
    productId: "flashing-tape-4in",
    name: 'Flashing Tape 4"',
    unit: "roll",
    unitPrice: 16.5,
    category: "Insulation",
  },

  // CONCRETE & MASONRY
  {
    productId: "sack-crete-80",
    name: "Concrete Mix 80 lb",
    unit: "bag",
    unitPrice: 5.6,
    category: "Concrete/Masonry",
  },
  {
    productId: "mortar-type-s-80",
    name: "Mortar Mix Type S 80 lb",
    unit: "bag",
    unitPrice: 8.9,
    category: "Concrete/Masonry",
  },
  {
    productId: "rebar-3-10mm-10ft",
    name: "Rebar #3 (10mm) 10ft",
    unit: "ea",
    unitPrice: 6.2,
    category: "Concrete/Masonry",
  },
  {
    productId: "remesh-6x6-10-10-5x10",
    name: "Remesh 6x6-10/10 5x10",
    unit: "sheet",
    unitPrice: 12.0,
    category: "Concrete/Masonry",
  },
  {
    productId: "sonotube-12x48",
    name: 'Sonotube 12" x 48"',
    unit: "ea",
    unitPrice: 17.5,
    category: "Concrete/Masonry",
  },
  {
    productId: "rebar-tie-wire-3-5lb",
    name: "Rebar Tie Wire 3.5 lb",
    unit: "roll",
    unitPrice: 6.9,
    category: "Concrete/Masonry",
  },
  {
    productId: "anchor-wedge-1-2x5-1-2",
    name: 'Wedge Anchor 1/2" x 5-1/2"',
    unit: "ea",
    unitPrice: 1.65,
    category: "Hardware",
  },

  // ROOFING
  {
    productId: "shingles-arch-bundle",
    name: "Architectural Shingles (bundle)",
    unit: "bundle",
    unitPrice: 34.0,
    category: "Roofing",
  },
  {
    productId: "felt-synthetic-10sq",
    name: "Synthetic Underlayment 10 sq",
    unit: "roll",
    unitPrice: 95.0,
    category: "Roofing",
  },
  {
    productId: "ice-water-shield-36x75",
    name: "Ice & Water Shield 36\" x 75'",
    unit: "roll",
    unitPrice: 129.0,
    category: "Roofing",
  },
  {
    productId: "drip-edge-alum-10ft",
    name: "Drip Edge Aluminum 10ft",
    unit: "len",
    unitPrice: 9.0,
    category: "Roofing",
  },
  {
    productId: "roof-nails-coil",
    name: "Roofing Nails (coil)",
    unit: "box",
    unitPrice: 48.0,
    category: "Fasteners",
  },
  {
    productId: "roof-vent-ridge-4ft",
    name: "Ridge Vent 4ft",
    unit: "ea",
    unitPrice: 12.5,
    category: "Roofing",
  },

  // EXTERIOR/SIDING & WINDOWS/DOORS
  {
    productId: "siding-lp-8in-16ft",
    name: 'Engineered Lap Siding 8" x 16ft',
    unit: "len",
    unitPrice: 18.5,
    category: "Siding",
  },
  {
    productId: "trim-pvc-1x4-18",
    name: "PVC Trim 1x4\"x18'",
    unit: "len",
    unitPrice: 26.0,
    category: "Siding",
  },
  {
    productId: "window-vinyl-3050",
    name: "Vinyl Window 3050",
    unit: "ea",
    unitPrice: 195.0,
    category: "Windows/Doors",
  },
  {
    productId: "ext-door-3068",
    name: "Exterior Door 3/0 x 6/8",
    unit: "ea",
    unitPrice: 239.0,
    category: "Windows/Doors",
  },
  {
    productId: "door-shim-pack",
    name: "Door Shims (pack)",
    unit: "pack",
    unitPrice: 3.0,
    category: "Hardware",
  },
  {
    productId: "spray-foam-lowexp",
    name: "Low-Expanding Foam (windows)",
    unit: "ea",
    unitPrice: 7.5,
    category: "Adhesives/Sealants",
  },

  // PAINT & FINISH
  {
    productId: "primer-int-1gal",
    name: "Interior Primer 1 gal",
    unit: "gal",
    unitPrice: 22.0,
    category: "Paint",
  },
  {
    productId: "paint-int-eggshell-1gal",
    name: "Interior Eggshell 1 gal",
    unit: "gal",
    unitPrice: 34.0,
    category: "Paint",
  },
  {
    productId: "paint-ext-satin-1gal",
    name: "Exterior Satin 1 gal",
    unit: "gal",
    unitPrice: 42.0,
    category: "Paint",
  },
  {
    productId: "roller-cover-3-8-2pk",
    name: 'Roller Covers 9" 3/8" (2pk)',
    unit: "pack",
    unitPrice: 6.0,
    category: "Paint",
  },
  {
    productId: "masking-paper-12in",
    name: 'Masking Paper 12"',
    unit: "roll",
    unitPrice: 4.1,
    category: "Paint",
  },
  {
    productId: "blue-tape-1-5in",
    name: 'Blue Tape 1.5"',
    unit: "roll",
    unitPrice: 4.9,
    category: "Paint",
  },

  // FLOORING
  {
    productId: "lvp-20mil-23-6sf",
    name: "LVP 20mil Wear Layer (23.6 sf)",
    unit: "box",
    unitPrice: 49.0,
    category: "Flooring",
  },
  {
    productId: "tile-porcelain-12x24",
    name: "Porcelain Tile 12x24",
    unit: "sqft",
    unitPrice: 2.4,
    category: "Flooring",
  },
  {
    productId: "thinset-modified-50lb",
    name: "Thinset Modified 50 lb",
    unit: "bag",
    unitPrice: 14.0,
    category: "Flooring",
  },
  {
    productId: "grout-sanded-25lb",
    name: "Grout Sanded 25 lb",
    unit: "bag",
    unitPrice: 11.5,
    category: "Flooring",
  },
  {
    productId: "underlayment-lvp-100sf",
    name: "Underlayment LVP 100 sf",
    unit: "roll",
    unitPrice: 22.0,
    category: "Flooring",
  },

  // PLUMBING (basic GC installs)
  {
    productId: "pvc-1-2-sch40-10ft",
    name: 'PVC Sch 40 1/2" x 10ft',
    unit: "len",
    unitPrice: 3.1,
    category: "Plumbing",
  },
  {
    productId: "pvc-3-4-sch40-10ft",
    name: 'PVC Sch 40 3/4" x 10ft',
    unit: "len",
    unitPrice: 4.1,
    category: "Plumbing",
  },
  {
    productId: "pvc-cement-clear-8oz",
    name: "PVC Cement (clear) 8oz",
    unit: "ea",
    unitPrice: 6.5,
    category: "Plumbing",
  },
  {
    productId: "pvc-primer-purple-8oz",
    name: "PVC Primer (purple) 8oz",
    unit: "ea",
    unitPrice: 6.5,
    category: "Plumbing",
  },
  {
    productId: "pex-a-1-2-100ft",
    name: 'PEX-A 1/2" 100ft',
    unit: "roll",
    unitPrice: 34.0,
    category: "Plumbing",
  },
  {
    productId: "sharkbite-1-2-tee",
    name: 'Push Tee 1/2"',
    unit: "ea",
    unitPrice: 8.9,
    category: "Plumbing",
  },
  {
    productId: "trap-1-1-2-kit",
    name: 'P-Trap Kit 1-1/2"',
    unit: "ea",
    unitPrice: 7.9,
    category: "Plumbing",
  },

  // HVAC (light GC scope)
  {
    productId: "flex-duct-6in-25ft",
    name: 'Flex Duct 6" x 25ft',
    unit: "ea",
    unitPrice: 36.0,
    category: "HVAC",
  },
  {
    productId: "mastic-1gal",
    name: "Duct Mastic 1 gal",
    unit: "gal",
    unitPrice: 29.0,
    category: "HVAC",
  },
  {
    productId: "foil-tape-2-5in-50yd",
    name: 'Foil Tape 2.5" x 50 yd',
    unit: "roll",
    unitPrice: 12.9,
    category: "HVAC",
  },

  // SITE / PROTECTION / SAFETY
  {
    productId: "poly-sheathing-10x100",
    name: "Poly Sheeting 10' x 100'",
    unit: "roll",
    unitPrice: 42.0,
    category: "Safety/Protection",
  },
  {
    productId: "ram-board-38x100",
    name: "Surface Protection Board 38\" x 100'",
    unit: "roll",
    unitPrice: 64.0,
    category: "Safety/Protection",
  },
  {
    productId: "mask-n95-20pk",
    name: "N95 Masks (20pk)",
    unit: "box",
    unitPrice: 19.0,
    category: "Safety/Protection",
  },
  {
    productId: "gloves-nitrile-100",
    name: "Nitrile Gloves (100)",
    unit: "box",
    unitPrice: 7.9,
    category: "Safety/Protection",
  },
  {
    productId: "contractor-bags-3mil-20",
    name: "Contractor Bags 3 mil (20)",
    unit: "box",
    unitPrice: 14.5,
    category: "Safety/Protection",
  },
];

/** ========== ELECTRICAL (MASTER ELECTRICIAN) ========== */
export const ELEC_CATALOG: MaterialItem[] = [
  // SERVICE & DISTRIBUTION
  {
    productId: "meter-socket-200a",
    name: "Meter Socket 200A",
    unit: "ea",
    unitPrice: 145.0,
    category: "Electrical",
  },
  {
    productId: "main-panel-200a-40c",
    name: "Main Panel 200A 40-circuit",
    unit: "ea",
    unitPrice: 229.0,
    category: "Electrical",
  },
  {
    productId: "subpanel-100a-20c",
    name: "Subpanel 100A 20-circuit",
    unit: "ea",
    unitPrice: 119.0,
    category: "Electrical",
  },
  {
    productId: "ground-rod-5-8x8",
    name: "Ground Rod 5/8\" x 8'",
    unit: "ea",
    unitPrice: 13.5,
    category: "Electrical",
  },
  {
    productId: "ground-clamp-5-8",
    name: 'Ground Rod Clamp 5/8"',
    unit: "ea",
    unitPrice: 4.5,
    category: "Electrical",
  },
  {
    productId: "ground-wire-6awg-bare-25ft",
    name: "Bare Copper #6 25ft",
    unit: "roll",
    unitPrice: 45.0,
    category: "Electrical",
  },
  {
    productId: "bonding-jumper-4awg",
    name: "Bonding Jumper #4",
    unit: "ea",
    unitPrice: 12.0,
    category: "Electrical",
  },
  {
    productId: "surge-whole-home",
    name: "Whole-Home Surge Protector",
    unit: "ea",
    unitPrice: 189.0,
    category: "Electrical",
  },

  // BREAKERS (examples—expand as needed)
  {
    productId: "breaker-1p-15a",
    name: "Breaker 1P 15A (Std)",
    unit: "ea",
    unitPrice: 6.9,
    category: "Electrical",
  },
  {
    productId: "breaker-1p-20a",
    name: "Breaker 1P 20A (Std)",
    unit: "ea",
    unitPrice: 7.4,
    category: "Electrical",
  },
  {
    productId: "breaker-2p-30a",
    name: "Breaker 2P 30A (Std)",
    unit: "ea",
    unitPrice: 18.5,
    category: "Electrical",
  },
  {
    productId: "breaker-2p-50a",
    name: "Breaker 2P 50A (Std)",
    unit: "ea",
    unitPrice: 24.0,
    category: "Electrical",
  },
  {
    productId: "breaker-1p-20a-afci",
    name: "Breaker 1P 20A AFCI",
    unit: "ea",
    unitPrice: 42.0,
    category: "Electrical",
  },
  {
    productId: "breaker-1p-20a-gfci",
    name: "Breaker 1P 20A GFCI",
    unit: "ea",
    unitPrice: 54.0,
    category: "Electrical",
  },
  {
    productId: "breaker-dualfunc-20a",
    name: "Breaker 1P 20A AFCI/GFCI",
    unit: "ea",
    unitPrice: 64.0,
    category: "Electrical",
  },

  // BOXES, COVERS, FITTINGS
  {
    productId: "box-nm-old-work-1g",
    name: "Old-Work Box 1-Gang (plastic)",
    unit: "ea",
    unitPrice: 1.58,
    category: "Electrical",
  },
  {
    productId: "box-nm-new-work-2g",
    name: "New-Work Box 2-Gang (plastic)",
    unit: "ea",
    unitPrice: 2.45,
    category: "Electrical",
  },
  {
    productId: "box-metal-4sq-1-1-2",
    name: '4" Square Box 1-1/2"',
    unit: "ea",
    unitPrice: 2.25,
    category: "Electrical",
  },
  {
    productId: "mud-ring-4sq-1g",
    name: '4" Sq Mud Ring 1-Gang',
    unit: "ea",
    unitPrice: 1.2,
    category: "Electrical",
  },
  {
    productId: "blank-cover-1g",
    name: "Blank Cover 1-Gang",
    unit: "ea",
    unitPrice: 0.75,
    category: "Electrical",
  },
  {
    productId: "mc-connector-3-8",
    name: 'MC Connector 3/8"',
    unit: "ea",
    unitPrice: 0.75,
    category: "Electrical",
  },
  {
    productId: "romex-connector-3-8",
    name: 'NM Connector 3/8"',
    unit: "ea",
    unitPrice: 0.55,
    category: "Electrical",
  },

  // CONDUIT & FITTINGS
  {
    productId: "emt-1-2-10ft",
    name: 'EMT 1/2" x 10ft',
    unit: "len",
    unitPrice: 7.2,
    category: "Electrical",
  },
  {
    productId: "emt-3-4-10ft",
    name: 'EMT 3/4" x 10ft',
    unit: "len",
    unitPrice: 10.5,
    category: "Electrical",
  },
  {
    productId: "emtlb-1-2",
    name: 'LB Conduit Body 1/2"',
    unit: "ea",
    unitPrice: 3.4,
    category: "Electrical",
  },
  {
    productId: "emt-elbow-1-2-90",
    name: 'EMT 90° Elbow 1/2"',
    unit: "ea",
    unitPrice: 1.9,
    category: "Electrical",
  },
  {
    productId: "emt-strap-1h-1-2",
    name: 'EMT Strap 1-Hole 1/2"',
    unit: "ea",
    unitPrice: 0.25,
    category: "Electrical",
  },
  {
    productId: "flex-sealtite-3-4-25ft",
    name: 'Liquidtight 3/4" 25ft',
    unit: "roll",
    unitPrice: 39.0,
    category: "Electrical",
  },
  {
    productId: "pvc-sch40-1in-10ft",
    name: 'PVC Conduit Sch40 1" x 10ft',
    unit: "len",
    unitPrice: 9.5,
    category: "Electrical",
  },
  {
    productId: "pvc-coupling-1in",
    name: 'PVC Coupling 1"',
    unit: "ea",
    unitPrice: 0.55,
    category: "Electrical",
  },

  // CABLE & WIRE
  {
    productId: "nm-14-2-250ft",
    name: "NM-B 14/2 250ft",
    unit: "roll",
    unitPrice: 92.0,
    category: "Electrical",
  },
  {
    productId: "nm-12-2-250ft",
    name: "NM-B 12/2 250ft",
    unit: "roll",
    unitPrice: 129.0,
    category: "Electrical",
  },
  {
    productId: "nm-12-3-250ft",
    name: "NM-B 12/3 250ft",
    unit: "roll",
    unitPrice: 189.0,
    category: "Electrical",
  },
  {
    productId: "uf-12-2-50ft",
    name: "UF-B 12/2 50ft (direct bury)",
    unit: "roll",
    unitPrice: 69.0,
    category: "Electrical",
  },
  {
    productId: "mc-12-2-250ft",
    name: "MC 12/2 250ft",
    unit: "roll",
    unitPrice: 178.0,
    category: "Electrical",
  },
  {
    productId: "thhn-12-black-500ft",
    name: "THHN #12 Black 500ft",
    unit: "roll",
    unitPrice: 89.0,
    category: "Electrical",
  },
  {
    productId: "thhn-12-white-500ft",
    name: "THHN #12 White 500ft",
    unit: "roll",
    unitPrice: 89.0,
    category: "Electrical",
  },
  {
    productId: "thhn-8-green-100ft",
    name: "THHN #8 Green 100ft (ground)",
    unit: "roll",
    unitPrice: 54.0,
    category: "Electrical",
  },
  {
    productId: "ser-4-4-4-2-50ft",
    name: "SER 4-4-4-2 50ft (subfeed)",
    unit: "roll",
    unitPrice: 289.0,
    category: "Electrical",
  },

  // DEVICES & PLATES
  {
    productId: "recept-15a-duplex",
    name: "Receptacle 15A Duplex",
    unit: "ea",
    unitPrice: 0.69,
    category: "Electrical",
  },
  {
    productId: "recept-20a-duplex",
    name: "Receptacle 20A Duplex",
    unit: "ea",
    unitPrice: 1.95,
    category: "Electrical",
  },
  {
    productId: "recept-gfci-20a",
    name: "GFCI 20A (WR/TR options)",
    unit: "ea",
    unitPrice: 15.5,
    category: "Electrical",
  },
  {
    productId: "switch-sp-15a",
    name: "Switch Single-Pole 15A",
    unit: "ea",
    unitPrice: 0.85,
    category: "Electrical",
  },
  {
    productId: "switch-3way-15a",
    name: "Switch 3-Way 15A",
    unit: "ea",
    unitPrice: 3.25,
    category: "Electrical",
  },
  {
    productId: "switch-dimmer-led",
    name: "LED Dimmer (Triac)",
    unit: "ea",
    unitPrice: 19.0,
    category: "Electrical",
  },
  {
    productId: "plate-decorator-1g",
    name: "Decorator Plate 1-Gang",
    unit: "ea",
    unitPrice: 0.6,
    category: "Electrical",
  },
  {
    productId: "plate-decorator-3g",
    name: "Decorator Plate 3-Gang",
    unit: "ea",
    unitPrice: 1.75,
    category: "Electrical",
  },
  {
    productId: "usb-recept-15a",
    name: "USB Combo Recept 15A",
    unit: "ea",
    unitPrice: 21.0,
    category: "Electrical",
  },
  {
    productId: "tamper-resistant-caps",
    name: "Tamper-Resistant Outlet Caps (12)",
    unit: "pack",
    unitPrice: 4.2,
    category: "Electrical",
  },

  // LIGHTING (common)
  {
    productId: "canless-6in-ct-adj",
    name: '6" Canless LED (CCT adj)',
    unit: "ea",
    unitPrice: 14.0,
    category: "Electrical",
  },
  {
    productId: "canless-4in-ct-adj",
    name: '4" Canless LED (CCT adj)',
    unit: "ea",
    unitPrice: 12.0,
    category: "Electrical",
  },
  {
    productId: "surface-led-13in",
    name: 'Surface LED 13" Disc',
    unit: "ea",
    unitPrice: 24.0,
    category: "Electrical",
  },
  {
    productId: "exterior-wall-pack",
    name: "Exterior Wall Pack LED",
    unit: "ea",
    unitPrice: 59.0,
    category: "Electrical",
  },
  {
    productId: "under-cab-led-24",
    name: 'Under-Cabinet LED 24"',
    unit: "ea",
    unitPrice: 32.0,
    category: "Electrical",
  },

  // SPECIALTY / APPLIANCE / EV
  {
    productId: "range-recept-50a-14-50r",
    name: "Range Recept 50A 14-50R",
    unit: "ea",
    unitPrice: 9.9,
    category: "Electrical",
  },
  {
    productId: "dryer-recept-30a-14-30r",
    name: "Dryer Recept 30A 14-30R",
    unit: "ea",
    unitPrice: 9.1,
    category: "Electrical",
  },
  {
    productId: "evse-50a-14-50",
    name: "EVSE 50A (NEMA 14-50 cordset)",
    unit: "ea",
    unitPrice: 399.0,
    category: "Electrical",
  },
  {
    productId: "disconnect-nonfus-60a",
    name: "AC Disconnect 60A Non-fusible",
    unit: "ea",
    unitPrice: 19.5,
    category: "Electrical",
  },
  {
    productId: "whip-ac-3-8-6ft",
    name: 'AC Whip 3/8" 6ft',
    unit: "ea",
    unitPrice: 12.5,
    category: "Electrical",
  },

  // CONSUMABLES / CONNECTORS
  {
    productId: "wirenut-yellow-100",
    name: "Wire Nuts (Yellow, 100)",
    unit: "box",
    unitPrice: 6.5,
    category: "Electrical",
  },
  {
    productId: "wirenut-blue-100",
    name: "Wire Nuts (Blue, 100)",
    unit: "box",
    unitPrice: 6.5,
    category: "Electrical",
  },
  {
    productId: "push-in-conn-6port",
    name: "Push-In Connectors 6-port (50)",
    unit: "box",
    unitPrice: 9.9,
    category: "Electrical",
  },
  {
    productId: "electrical-tape-pro",
    name: "Electrical Tape (pro grade)",
    unit: "ea",
    unitPrice: 2.5,
    category: "Electrical",
  },
  {
    productId: "bushing-1-2",
    name: 'Plastic Bushing 1/2"',
    unit: "ea",
    unitPrice: 0.2,
    category: "Electrical",
  },
  {
    productId: "anti-ox-1-oz",
    name: "Anti-Ox Compound 1oz",
    unit: "ea",
    unitPrice: 5.9,
    category: "Electrical",
  },
];

/** ========== COMBINED CATALOG ========== */
export const CATALOG: MaterialItem[] = [...GC_CATALOG, ...ELEC_CATALOG];
