// modules/catalog/seed.ts
export type Category = { id: string; name: string };
export type Product = {
  id: string;
  categoryId: string;
  name: string;
  unit: string; // "ea", "sheet", "10ft", "box"
  unitPrice: number; // baseline seed price
  retailer?: string; // Optional: "homedepot", "lowes", "menards", etc.
  dataSource?: string; // Optional: "ai_estimated", "retailer_scraped", etc.
};

export const CATEGORIES: Category[] = [
  { id: "framing", name: "Framing" },
  { id: "fasteners", name: "Fasteners" },
  { id: "drywall", name: "Drywall" },
  { id: "electrical", name: "Electrical" },
  { id: "plumbing", name: "Plumbing" },
  { id: "roofing", name: "Roofing" },
  { id: "masonry", name: "Masonry" },
];

export const PRODUCTS_SEED: Record<string, Product[]> = {
  framing: [
    {
      id: "stud-2x4x8",
      categoryId: "framing",
      name: "2x4x8 KD Stud",
      unit: "ea",
      unitPrice: 3.45,
    },
    {
      id: "stud-2x4x92-5-8",
      categoryId: "framing",
      name: "2x4x92-5/8 Precut Stud",
      unit: "ea",
      unitPrice: 3.65,
    },
    {
      id: "stud-2x6x8",
      categoryId: "framing",
      name: "2x6x8 KD Stud",
      unit: "ea",
      unitPrice: 6.25,
    },
    {
      id: "plate-2x4",
      categoryId: "framing",
      name: "2x4 Plate (10 ft)",
      unit: "10ft",
      unitPrice: 6.9,
    },
    {
      id: "plate-2x4-12",
      categoryId: "framing",
      name: "2x4 Plate (12 ft)",
      unit: "12ft",
      unitPrice: 8.15,
    },
    {
      id: "plate-2x6-10",
      categoryId: "framing",
      name: "2x6 Plate (10 ft)",
      unit: "10ft",
      unitPrice: 11.50,
    },
    {
      id: "osb-7-16-4x8",
      categoryId: "framing",
      name: "OSB 7/16 in 4x8",
      unit: "sheet",
      unitPrice: 14.25,
    },
    {
      id: "plywood-3-4-4x8",
      categoryId: "framing",
      name: "Plywood 3/4 in 4x8",
      unit: "sheet",
      unitPrice: 48.50,
    },
    {
      id: "header-lvl-2x10",
      categoryId: "framing",
      name: "LVL Header 2x10 (12 ft)",
      unit: "ea",
      unitPrice: 54.00,
    },
    {
      id: "joist-hanger-2x8",
      categoryId: "framing",
      name: "Joist Hanger 2x8",
      unit: "ea",
      unitPrice: 1.85,
    },
    {
      id: "nails-16d-framing",
      categoryId: "framing",
      name: "16d Framing Nails (5 lb box)",
      unit: "box",
      unitPrice: 18.50,
    },
    {
      id: "nails-8d-common",
      categoryId: "framing",
      name: "8d Common Nails (5 lb box)",
      unit: "box",
      unitPrice: 16.25,
    },
  ],
  drywall: [
    {
      id: "sheet-1-2-4x8",
      categoryId: "drywall",
      name: "Drywall 1/2 in 4x8",
      unit: "sheet",
      unitPrice: 11.75,
    },
    {
      id: "sheet-5-8-4x8",
      categoryId: "drywall",
      name: "Drywall 5/8 in 4x8 (Fire-Rated)",
      unit: "sheet",
      unitPrice: 14.25,
    },
    {
      id: "sheet-1-2-4x12",
      categoryId: "drywall",
      name: "Drywall 1/2 in 4x12",
      unit: "sheet",
      unitPrice: 17.50,
    },
    {
      id: "screws-1-1-4",
      categoryId: "drywall",
      name: "Drywall Screws 1-1/4 in (1 lb)",
      unit: "box",
      unitPrice: 6.5,
    },
    {
      id: "compound-all-purpose",
      categoryId: "drywall",
      name: "Joint Compound All-Purpose (5 gal)",
      unit: "bucket",
      unitPrice: 18.75,
    },
    {
      id: "tape-paper",
      categoryId: "drywall",
      name: "Paper Drywall Tape (500 ft)",
      unit: "roll",
      unitPrice: 8.25,
    },
    {
      id: "corner-bead-8ft",
      categoryId: "drywall",
      name: "Metal Corner Bead (8 ft)",
      unit: "ea",
      unitPrice: 2.45,
    },
  ],
  electrical: [
    {
      id: "nmb-12-2-250",
      categoryId: "electrical",
      name: "NM-B 12/2 (250 ft)",
      unit: "roll",
      unitPrice: 112.0,
    },
    {
      id: "nmb-14-2-250",
      categoryId: "electrical",
      name: "NM-B 14/2 (250 ft)",
      unit: "roll",
      unitPrice: 85.0,
    },
    {
      id: "nmb-12-3-100",
      categoryId: "electrical",
      name: "NM-B 12/3 (100 ft)",
      unit: "roll",
      unitPrice: 78.0,
    },
    {
      id: "box-single",
      categoryId: "electrical",
      name: "Single-Gang Box (old work)",
      unit: "ea",
      unitPrice: 1.25,
    },
    {
      id: "box-double",
      categoryId: "electrical",
      name: "Double-Gang Box (old work)",
      unit: "ea",
      unitPrice: 2.15,
    },
    {
      id: "box-ceiling",
      categoryId: "electrical",
      name: "Ceiling Box w/ Bracket",
      unit: "ea",
      unitPrice: 3.45,
    },
    {
      id: "outlet-15a",
      categoryId: "electrical",
      name: "15A Duplex Receptacle",
      unit: "ea",
      unitPrice: 0.85,
    },
    {
      id: "outlet-20a",
      categoryId: "electrical",
      name: "20A Duplex Receptacle",
      unit: "ea",
      unitPrice: 1.45,
    },
    {
      id: "gfci-15a",
      categoryId: "electrical",
      name: "15A GFCI Receptacle",
      unit: "ea",
      unitPrice: 12.50,
    },
    {
      id: "switch-single",
      categoryId: "electrical",
      name: "Single-Pole Switch",
      unit: "ea",
      unitPrice: 0.95,
    },
    {
      id: "switch-3way",
      categoryId: "electrical",
      name: "3-Way Switch",
      unit: "ea",
      unitPrice: 1.85,
    },
    {
      id: "breaker-15a",
      categoryId: "electrical",
      name: "15A Circuit Breaker",
      unit: "ea",
      unitPrice: 6.75,
    },
    {
      id: "breaker-20a",
      categoryId: "electrical",
      name: "20A Circuit Breaker",
      unit: "ea",
      unitPrice: 7.25,
    },
    {
      id: "wire-nuts-red",
      categoryId: "electrical",
      name: "Wire Nuts - Red (100 pack)",
      unit: "box",
      unitPrice: 8.50,
    },
    {
      id: "wire-nuts-yellow",
      categoryId: "electrical",
      name: "Wire Nuts - Yellow (100 pack)",
      unit: "box",
      unitPrice: 7.75,
    },
    {
      id: "staples-cable",
      categoryId: "electrical",
      name: "Cable Staples (100 pack)",
      unit: "box",
      unitPrice: 5.25,
    },
    {
      id: "panel-cover-single",
      categoryId: "electrical",
      name: "Single-Gang Wall Plate",
      unit: "ea",
      unitPrice: 0.65,
    },
    {
      id: "panel-cover-double",
      categoryId: "electrical",
      name: "Double-Gang Wall Plate",
      unit: "ea",
      unitPrice: 1.15,
    },
  ],
  plumbing: [
    {
      id: "pex-a-1-2-100",
      categoryId: "plumbing",
      name: "PEX-A 1/2 in (100 ft)",
      unit: "coil",
      unitPrice: 42.0,
    },
    {
      id: "angle-stop-1-2",
      categoryId: "plumbing",
      name: "Angle Stop 1/2 in x 3/8 in",
      unit: "ea",
      unitPrice: 6.2,
    },
  ],
};
