-- Add search_name column for normalized product search
-- This column contains all search variations (e.g., "2x8 2-in x 8-in pressure treated lumber")
-- Generated by sync-xbyte during product upsert

ALTER TABLE products ADD COLUMN IF NOT EXISTS search_name TEXT;

-- Index for efficient text search on search_name
CREATE INDEX IF NOT EXISTS idx_products_search_name ON products(search_name);

-- Comment for documentation
COMMENT ON COLUMN products.search_name IS 'Normalized product name with all search variations (2x8, 2-in x 8-in, etc.) for improved FTS matching';
